export default [
  {selected: false, value: 'Afghanistan', key: 'AF'},
  {selected: false, value: 'Åland Islands', key: 'AX'},
  {selected: false, value: 'Albania', key: 'AL'},
  {selected: false, value: 'Algeria', key: 'DZ'},
  {selected: false, value: 'American Samoa', key: 'AS'},
  {selected: false, value: 'AndorrA', key: 'AD'},
  {selected: false, value: 'Angola', key: 'AO'},
  {selected: false, value: 'Anguilla', key: 'AI'},
  {selected: false, value: 'Antarctica', key: 'AQ'},
  {selected: false, value: 'Antigua and Barbuda', key: 'AG'},
  {selected: false, value: 'Argentina', key: 'AR'},
  {selected: false, value: 'Armenia', key: 'AM'},
  {selected: false, value: 'Aruba', key: 'AW'},
  {selected: false, value: 'Australia', key: 'AU'},
  {selected: false, value: 'Austria', key: 'AT'},
  {selected: false, value: 'Azerbaijan', key: 'AZ'},
  {selected: false, value: 'Bahamas', key: 'BS'},
  {selected: false, value: 'Bahrain', key: 'BH'},
  {selected: false, value: 'Bangladesh', key: 'BD'},
  {selected: false, value: 'Barbados', key: 'BB'},
  {selected: false, value: 'Belarus', key: 'BY'},
  {selected: false, value: 'Belgium', key: 'BE'},
  {selected: false, value: 'Belize', key: 'BZ'},
  {selected: false, value: 'Benin', key: 'BJ'},
  {selected: false, value: 'Bermuda', key: 'BM'},
  {selected: false, value: 'Bhutan', key: 'BT'},
  {selected: false, value: 'Bolivia', key: 'BO'},
  {selected: false, value: 'Bosnia and Herzegovina', key: 'BA'},
  {selected: false, value: 'Botswana', key: 'BW'},
  {selected: false, value: 'Bouvet Island', key: 'BV'},
  {selected: false, value: 'Brazil', key: 'BR'},
  {selected: false, value: 'British Indian Ocean Territory', key: 'IO'},
  {selected: false, value: 'Brunei Darussalam', key: 'BN'},
  {selected: false, value: 'Bulgaria', key: 'BG'},
  {selected: false, value: 'Burkina Faso', key: 'BF'},
  {selected: false, value: 'Burundi', key: 'BI'},
  {selected: false, value: 'Cambodia', key: 'KH'},
  {selected: false, value: 'Cameroon', key: 'CM'},
  {selected: false, value: 'Canada', key: 'CA'},
  {selected: false, value: 'Cape Verde', key: 'CV'},
  {selected: false, value: 'Cayman Islands', key: 'KY'},
  {selected: false, value: 'Central African Republic', key: 'CF'},
  {selected: false, value: 'Chad', key: 'TD'},
  {selected: false, value: 'Chile', key: 'CL'},
  {selected: false, value: 'China', key: 'CN'},
  {selected: false, value: 'Christmas Island', key: 'CX'},
  {selected: false, value: 'Cocos (Keeling) Islands', key: 'CC'},
  {selected: false, value: 'Colombia', key: 'CO'},
  {selected: false, value: 'Comoros', key: 'KM'},
  {selected: false, value: 'Congo', key: 'CG'},
  {selected: false, value: 'Congo, The Democratic Republic of the', key: 'CD'},
  {selected: false, value: 'Cook Islands', key: 'CK'},
  {selected: false, value: 'Costa Rica', key: 'CR'},
  {selected: false, value: 'Cote D\'Ivoire', key: 'CI'},
  {selected: false, value: 'Croatia', key: 'HR'},
  {selected: false, value: 'Cuba', key: 'CU'},
  {selected: false, value: 'Cyprus', key: 'CY'},
  {selected: false, value: 'Czech Republic', key: 'CZ'},
  {selected: false, value: 'Denmark', key: 'DK'},
  {selected: false, value: 'Djibouti', key: 'DJ'},
  {selected: false, value: 'Dominica', key: 'DM'},
  {selected: false, value: 'Dominican Republic', key: 'DO'},
  {selected: false, value: 'Ecuador', key: 'EC'},
  {selected: false, value: 'Egypt', key: 'EG'},
  {selected: false, value: 'El Salvador', key: 'SV'},
  {selected: false, value: 'Equatorial Guinea', key: 'GQ'},
  {selected: false, value: 'Eritrea', key: 'ER'},
  {selected: false, value: 'Estonia', key: 'EE'},
  {selected: false, value: 'Ethiopia', key: 'ET'},
  {selected: false, value: 'Falkland Islands (Malvinas)', key: 'FK'},
  {selected: false, value: 'Faroe Islands', key: 'FO'},
  {selected: false, value: 'Fiji', key: 'FJ'},
  {selected: false, value: 'Finland', key: 'FI'},
  {selected: false, value: 'France', key: 'FR'},
  {selected: false, value: 'French Guiana', key: 'GF'},
  {selected: false, value: 'French Polynesia', key: 'PF'},
  {selected: false, value: 'French Southern Territories', key: 'TF'},
  {selected: false, value: 'Gabon', key: 'GA'},
  {selected: false, value: 'Gambia', key: 'GM'},
  {selected: false, value: 'Georgia', key: 'GE'},
  {selected: false, value: 'Germany', key: 'DE'},
  {selected: false, value: 'Ghana', key: 'GH'},
  {selected: false, value: 'Gibraltar', key: 'GI'},
  {selected: false, value: 'Greece', key: 'GR'},
  {selected: false, value: 'Greenland', key: 'GL'},
  {selected: false, value: 'Grenada', key: 'GD'},
  {selected: false, value: 'Guadeloupe', key: 'GP'},
  {selected: false, value: 'Guam', key: 'GU'},
  {selected: false, value: 'Guatemala', key: 'GT'},
  {selected: false, value: 'Guernsey', key: 'GG'},
  {selected: false, value: 'Guinea', key: 'GN'},
  {selected: false, value: 'Guinea-Bissau', key: 'GW'},
  {selected: false, value: 'Guyana', key: 'GY'},
  {selected: false, value: 'Haiti', key: 'HT'},
  {selected: false, value: 'Heard Island and Mcdonald Islands', key: 'HM'},
  {selected: false, value: 'Holy See (Vatican City State)', key: 'VA'},
  {selected: false, value: 'Honduras', key: 'HN'},
  {selected: false, value: 'Hong Kong', key: 'HK'},
  {selected: false, value: 'Hungary', key: 'HU'},
  {selected: false, value: 'Iceland', key: 'IS'},
  {selected: false, value: 'India', key: 'IN'},
  {selected: false, value: 'Indonesia', key: 'ID'},
  {selected: false, value: 'Iran, Islamic Republic Of', key: 'IR'},
  {selected: false, value: 'Iraq', key: 'IQ'},
  {selected: false, value: 'Ireland', key: 'IE'},
  {selected: false, value: 'Isle of Man', key: 'IM'},
  {selected: false, value: 'Israel', key: 'IL'},
  {selected: false, value: 'Italy', key: 'IT'},
  {selected: false, value: 'Jamaica', key: 'JM'},
  {selected: false, value: 'Japan', key: 'JP'},
  {selected: false, value: 'Jersey', key: 'JE'},
  {selected: false, value: 'Jordan', key: 'JO'},
  {selected: false, value: 'Kazakhstan', key: 'KZ'},
  {selected: false, value: 'Kenya', key: 'KE'},
  {selected: false, value: 'Kiribati', key: 'KI'},
  {selected: false, value: 'Korea, Democratic People\'S Republic of', key: 'KP'},
  {selected: false, value: 'Korea, Republic of', key: 'KR'},
  {selected: false, value: 'Kuwait', key: 'KW'},
  {selected: false, value: 'Kyrgyzstan', key: 'KG'},
  {selected: false, value: 'Lao People\'S Democratic Republic', key: 'LA'},
  {selected: false, value: 'Latvia', key: 'LV'},
  {selected: false, value: 'Lebanon', key: 'LB'},
  {selected: false, value: 'Lesotho', key: 'LS'},
  {selected: false, value: 'Liberia', key: 'LR'},
  {selected: false, value: 'Libyan Arab Jamahiriya', key: 'LY'},
  {selected: false, value: 'Liechtenstein', key: 'LI'},
  {selected: false, value: 'Lithuania', key: 'LT'},
  {selected: false, value: 'Luxembourg', key: 'LU'},
  {selected: false, value: 'Macao', key: 'MO'},
  {selected: false, value: 'Macedonia, The Former Yugoslav Republic of', key: 'MK'},
  {selected: false, value: 'Madagascar', key: 'MG'},
  {selected: false, value: 'Malawi', key: 'MW'},
  {selected: false, value: 'Malaysia', key: 'MY'},
  {selected: false, value: 'Maldives', key: 'MV'},
  {selected: false, value: 'Mali', key: 'ML'},
  {selected: false, value: 'Malta', key: 'MT'},
  {selected: false, value: 'Marshall Islands', key: 'MH'},
  {selected: false, value: 'Martinique', key: 'MQ'},
  {selected: false, value: 'Mauritania', key: 'MR'},
  {selected: false, value: 'Mauritius', key: 'MU'},
  {selected: false, value: 'Mayotte', key: 'YT'},
  {selected: false, value: 'Mexico', key: 'MX'},
  {selected: false, value: 'Micronesia, Federated States of', key: 'FM'},
  {selected: false, value: 'Moldova, Republic of', key: 'MD'},
  {selected: false, value: 'Monaco', key: 'MC'},
  {selected: false, value: 'Mongolia', key: 'MN'},
  {selected: false, value: 'Montserrat', key: 'MS'},
  {selected: false, value: 'Morocco', key: 'MA'},
  {selected: false, value: 'Mozambique', key: 'MZ'},
  {selected: false, value: 'Myanmar', key: 'MM'},
  {selected: false, value: 'Namibia', key: 'NA'},
  {selected: false, value: 'Nauru', key: 'NR'},
  {selected: false, value: 'Nepal', key: 'NP'},
  {selected: false, value: 'Netherlands', key: 'NL'},
  {selected: false, value: 'Netherlands Antilles', key: 'AN'},
  {selected: false, value: 'New Caledonia', key: 'NC'},
  {selected: false, value: 'New Zealand', key: 'NZ'},
  {selected: false, value: 'Nicaragua', key: 'NI'},
  {selected: false, value: 'Niger', key: 'NE'},
  {selected: false, value: 'Nigeria', key: 'NG'},
  {selected: false, value: 'Niue', key: 'NU'},
  {selected: false, value: 'Norfolk Island', key: 'NF'},
  {selected: false, value: 'Northern Mariana Islands', key: 'MP'},
  {selected: false, value: 'Norway', key: 'NO'},
  {selected: false, value: 'Oman', key: 'OM'},
  {selected: false, value: 'Pakistan', key: 'PK'},
  {selected: false, value: 'Palau', key: 'PW'},
  {selected: false, value: 'Palestinian Territory, Occupied', key: 'PS'},
  {selected: false, value: 'Panama', key: 'PA'},
  {selected: false, value: 'Papua New Guinea', key: 'PG'},
  {selected: false, value: 'Paraguay', key: 'PY'},
  {selected: false, value: 'Peru', key: 'PE'},
  {selected: false, value: 'Philippines', key: 'PH'},
  {selected: false, value: 'Pitcairn', key: 'PN'},
  {selected: false, value: 'Poland', key: 'PL'},
  {selected: false, value: 'Portugal', key: 'PT'},
  {selected: false, value: 'Puerto Rico', key: 'PR'},
  {selected: false, value: 'Qatar', key: 'QA'},
  {selected: false, value: 'Reunion', key: 'RE'},
  {selected: false, value: 'Romania', key: 'RO'},
  {selected: false, value: 'Russian Federation', key: 'RU'},
  {selected: false, value: 'RWANDA', key: 'RW'},
  {selected: false, value: 'Saint Helena', key: 'SH'},
  {selected: false, value: 'Saint Kitts and Nevis', key: 'KN'},
  {selected: false, value: 'Saint Lucia', key: 'LC'},
  {selected: false, value: 'Saint Pierre and Miquelon', key: 'PM'},
  {selected: false, value: 'Saint Vincent and the Grenadines', key: 'VC'},
  {selected: false, value: 'Samoa', key: 'WS'},
  {selected: false, value: 'San Marino', key: 'SM'},
  {selected: false, value: 'Sao Tome and Principe', key: 'ST'},
  {selected: false, value: 'Saudi Arabia', key: 'SA'},
  {selected: false, value: 'Senegal', key: 'SN'},
  {selected: false, value: 'Serbia and Montenegro', key: 'CS'},
  {selected: false, value: 'Seychelles', key: 'SC'},
  {selected: false, value: 'Sierra Leone', key: 'SL'},
  {selected: false, value: 'Singapore', key: 'SG'},
  {selected: false, value: 'Slovakia', key: 'SK'},
  {selected: false, value: 'Slovenia', key: 'SI'},
  {selected: false, value: 'Solomon Islands', key: 'SB'},
  {selected: false, value: 'Somalia', key: 'SO'},
  {selected: false, value: 'South Africa', key: 'ZA'},
  {selected: false, value: 'South Georgia and the South Sandwich Islands', key: 'GS'},
  {selected: false, value: 'Spain', key: 'ES'},
  {selected: false, value: 'Sri Lanka', key: 'LK'},
  {selected: false, value: 'Sudan', key: 'SD'},
  {selected: false, value: 'Suriselected: false, value', key: 'SR'},
  {selected: false, value: 'Svalbard and Jan Mayen', key: 'SJ'},
  {selected: false, value: 'Swaziland', key: 'SZ'},
  {selected: false, value: 'Sweden', key: 'SE'},
  {selected: false, value: 'Switzerland', key: 'CH'},
  {selected: false, value: 'Syrian Arab Republic', key: 'SY'},
  {selected: false, value: 'Taiwan, Province of China', key: 'TW'},
  {selected: false, value: 'Tajikistan', key: 'TJ'},
  {selected: false, value: 'Tanzania, United Republic of', key: 'TZ'},
  {selected: false, value: 'Thailand', key: 'TH'},
  {selected: false, value: 'Timor-Leste', key: 'TL'},
  {selected: false, value: 'Togo', key: 'TG'},
  {selected: false, value: 'Tokelau', key: 'TK'},
  {selected: false, value: 'Tonga', key: 'TO'},
  {selected: false, value: 'Trinidad and Tobago', key: 'TT'},
  {selected: false, value: 'Tunisia', key: 'TN'},
  {selected: false, value: 'Turkey', key: 'TR'},
  {selected: false, value: 'Turkmenistan', key: 'TM'},
  {selected: false, value: 'Turks and Caicos Islands', key: 'TC'},
  {selected: false, value: 'Tuvalu', key: 'TV'},
  {selected: false, value: 'Uganda', key: 'UG'},
  {selected: false, value: 'Ukraine', key: 'UA'},
  {selected: false, value: 'United Arab Emirates', key: 'AE'},
  {selected: false, value: 'United Kingdom', key: 'GB'},
  {selected: false, value: 'United States', key: 'US'},
  {selected: false, value: 'United States Minor Outlying Islands', key: 'UM'},
  {selected: false, value: 'Uruguay', key: 'UY'},
  {selected: false, value: 'Uzbekistan', key: 'UZ'},
  {selected: false, value: 'Vanuatu', key: 'VU'},
  {selected: false, value: 'Venezuela', key: 'VE'},
  {selected: false, value: 'Viet Nam', key: 'VN'},
  {selected: false, value: 'Virgin Islands, British', key: 'VG'},
  {selected: false, value: 'Virgin Islands, U.S.', key: 'VI'},
  {selected: false, value: 'Wallis and Futuna', key: 'WF'},
  {selected: false, value: 'Western Sahara', key: 'EH'},
  {selected: false, value: 'Yemen', key: 'YE'},
  {selected: false, value: 'Zambia', key: 'ZM'},
  {selected: false, value: 'Zimbabwe', key: 'ZW'}
]
