export default [
    {key: "GENERAL AGRICULTURE", value: "GENERAL AGRICULTURE", selected: false},
    {key: "AGRICULTURE PRODUCTION AND MANAGEMENT", value: "AGRICULTURE PRODUCTION AND MANAGEMENT", selected: false},
    {key: "AGRICULTURAL ECONOMICS", value: "AGRICULTURAL ECONOMICS", selected: false},
    {key: "ANIMAL SCIENCES", value: "ANIMAL SCIENCES", selected: false},
    {key: "FOOD SCIENCE", value: "FOOD SCIENCE", selected: false},
    {key: "PLANT SCIENCE AND AGRONOMY", value: "PLANT SCIENCE AND AGRONOMY", selected: false},
    {key: "SOIL SCIENCE", value: "SOIL SCIENCE", selected: false},
    {key: "MISCELLANEOUS AGRICULTURE", value: "MISCELLANEOUS AGRICULTURE", selected: false},
    {key: "FORESTRY", value: "FORESTRY", selected: false},
    {key: "NATURAL RESOURCES MANAGEMENT", value: "NATURAL RESOURCES MANAGEMENT", selected: false},
    {key: "FINE ARTS", value: "FINE ARTS", selected: false},
    {key: "DRAMA AND THEATER ARTS", value: "DRAMA AND THEATER ARTS", selected: false},
    {key: "MUSIC", value: "MUSIC", selected: false},
    {key: "VISUAL AND PERFORMING ARTS", value: "VISUAL AND PERFORMING ARTS", selected: false},
    {key: "COMMERCIAL ART AND GRAPHIC DESIGN", value: "COMMERCIAL ART AND GRAPHIC DESIGN", selected: false},
    {key: "FILM VIDEO AND PHOTOGRAPHIC ARTS", value: "FILM VIDEO AND PHOTOGRAPHIC ARTS", selected: false},
    {key: "STUDIO ARTS", value: "STUDIO ARTS", selected: false},
    {key: "MISCELLANEOUS FINE ARTS", value: "MISCELLANEOUS FINE ARTS", selected: false},
    {key: "ENVIRONMENTAL SCIENCE", value: "ENVIRONMENTAL SCIENCE", selected: false},
    {key: "BIOLOGY", value: "BIOLOGY", selected: false},
    {key: "BIOCHEMICAL SCIENCES", value: "BIOCHEMICAL SCIENCES", selected: false},
    {key: "BOTANY", value: "BOTANY", selected: false},
    {key: "MOLECULAR BIOLOGY", value: "MOLECULAR BIOLOGY", selected: false},
    {key: "ECOLOGY", value: "ECOLOGY", selected: false},
    {key: "GENETICS", value: "GENETICS", selected: false},
    {key: "MICROBIOLOGY", value: "MICROBIOLOGY", selected: false},
    {key: "PHARMACOLOGY", value: "PHARMACOLOGY", selected: false},
    {key: "PHYSIOLOGY", value: "PHYSIOLOGY", selected: false},
    {key: "ZOOLOGY", value: "ZOOLOGY", selected: false},
    {key: "NEUROSCIENCE", value: "NEUROSCIENCE", selected: false},
    {key: "MISCELLANEOUS BIOLOGY", value: "MISCELLANEOUS BIOLOGY", selected: false},
    {key: "COGNITIVE SCIENCE AND BIOPSYCHOLOGY", value: "COGNITIVE SCIENCE AND BIOPSYCHOLOGY", selected: false},
    {key: "GENERAL BUSINESS", value: "GENERAL BUSINESS", selected: false},
    {key: "ACCOUNTING", value: "ACCOUNTING", selected: false},
    {key: "ACTUARIAL SCIENCE", value: "ACTUARIAL SCIENCE", selected: false},
    {key: "BUSINESS MANAGEMENT AND ADMINISTRATION", value: "BUSINESS MANAGEMENT AND ADMINISTRATION", selected: false},
    {key: "OPERATIONS LOGISTICS AND E-COMMERCE", value: "OPERATIONS LOGISTICS AND E-COMMERCE", selected: false},
    {key: "BUSINESS ECONOMICS", value: "BUSINESS ECONOMICS", selected: false},
    {key: "MARKETING AND MARKETING RESEARCH", value: "MARKETING AND MARKETING RESEARCH", selected: false},
    {key: "FINANCE", value: "FINANCE", selected: false},
    {key: "HUMAN RESOURCES AND PERSONNEL MANAGEMENT", value: "HUMAN RESOURCES AND PERSONNEL MANAGEMENT", selected: false},
    {key: "INTERNATIONAL BUSINESS", value: "INTERNATIONAL BUSINESS", selected: false},
    {key: "HOSPITALITY MANAGEMENT", value: "HOSPITALITY MANAGEMENT", selected: false},
    {key: "MANAGEMENT INFORMATION SYSTEMS AND STATISTICS", value: "MANAGEMENT INFORMATION SYSTEMS AND STATISTICS", selected: false},
    {key: "MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION", value: "MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION", selected: false},
    {key: "COMMUNICATIONS", value: "COMMUNICATIONS", selected: false},
    {key: "JOURNALISM", value: "JOURNALISM", selected: false},
    {key: "MASS MEDIA", value: "MASS MEDIA", selected: false},
    {key: "ADVERTISING AND PUBLIC RELATIONS", value: "ADVERTISING AND PUBLIC RELATIONS", selected: false},
    {key: "COMMUNICATION TECHNOLOGIES", value: "COMMUNICATION TECHNOLOGIES", selected: false},
    {key: "COMPUTER AND INFORMATION SYSTEMS", value: "COMPUTER AND INFORMATION SYSTEMS", selected: false},
    {key: "COMPUTER PROGRAMMING AND DATA PROCESSING", value: "COMPUTER PROGRAMMING AND DATA PROCESSING", selected: false},
    {key: "COMPUTER SCIENCE", value: "COMPUTER SCIENCE", selected: false},
    {key: "INFORMATION SCIENCES", value: "INFORMATION SCIENCES", selected: false},
    {key: "COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY", value: "COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY", selected: false},
    {key: "COMPUTER NETWORKING AND TELECOMMUNICATIONS", value: "COMPUTER NETWORKING AND TELECOMMUNICATIONS", selected: false},
    {key: "MATHEMATICS", value: "MATHEMATICS", selected: false},
    {key: "APPLIED MATHEMATICS", value: "APPLIED MATHEMATICS", selected: false},
    {key: "STATISTICS AND DECISION SCIENCE", value: "STATISTICS AND DECISION SCIENCE", selected: false},
    {key: "MATHEMATICS AND COMPUTER SCIENCE", value: "MATHEMATICS AND COMPUTER SCIENCE", selected: false},
    {key: "GENERAL EDUCATION", value: "GENERAL EDUCATION", selected: false},
    {key: "EDUCATIONAL ADMINISTRATION AND SUPERVISION", value: "EDUCATIONAL ADMINISTRATION AND SUPERVISION", selected: false},
    {key: "SCHOOL STUDENT COUNSELING", value: "SCHOOL STUDENT COUNSELING", selected: false},
    {key: "ELEMENTARY EDUCATION", value: "ELEMENTARY EDUCATION", selected: false},
    {key: "MATHEMATICS TEACHER EDUCATION", value: "MATHEMATICS TEACHER EDUCATION", selected: false},
    {key: "PHYSICAL AND HEALTH EDUCATION TEACHING", value: "PHYSICAL AND HEALTH EDUCATION TEACHING", selected: false},
    {key: "EARLY CHILDHOOD EDUCATION", value: "EARLY CHILDHOOD EDUCATION", selected: false},
    {key: "SCIENCE AND COMPUTER TEACHER EDUCATION", value: "SCIENCE AND COMPUTER TEACHER EDUCATION", selected: false},
    {key: "SECONDARY TEACHER EDUCATION", value: "SECONDARY TEACHER EDUCATION", selected: false},
    {key: "SPECIAL NEEDS EDUCATION", value: "SPECIAL NEEDS EDUCATION", selected: false},
    {key: "SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION", value: "SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION", selected: false},
    {key: "TEACHER EDUCATION: MULTIPLE LEVELS", value: "TEACHER EDUCATION: MULTIPLE LEVELS", selected: false},
    {key: "LANGUAGE AND DRAMA EDUCATION", value: "LANGUAGE AND DRAMA EDUCATION", selected: false},
    {key: "ART AND MUSIC EDUCATION", value: "ART AND MUSIC EDUCATION", selected: false},
    {key: "MISCELLANEOUS EDUCATION", value: "MISCELLANEOUS EDUCATION", selected: false},
    {key: "LIBRARY SCIENCE", value: "LIBRARY SCIENCE", selected: false},
    {key: "ARCHITECTURE", value: "ARCHITECTURE", selected: false},
    {key: "GENERAL ENGINEERING", value: "GENERAL ENGINEERING", selected: false},
    {key: "AEROSPACE ENGINEERING", value: "AEROSPACE ENGINEERING", selected: false},
    {key: "BIOLOGICAL ENGINEERING", value: "BIOLOGICAL ENGINEERING", selected: false},
    {key: "ARCHITECTURAL ENGINEERING", value: "ARCHITECTURAL ENGINEERING", selected: false},
    {key: "BIOMEDICAL ENGINEERING", value: "BIOMEDICAL ENGINEERING", selected: false},
    {key: "CHEMICAL ENGINEERING", value: "CHEMICAL ENGINEERING", selected: false},
    {key: "CIVIL ENGINEERING", value: "CIVIL ENGINEERING", selected: false},
    {key: "COMPUTER ENGINEERING", value: "COMPUTER ENGINEERING", selected: false},
    {key: "ELECTRICAL ENGINEERING", value: "ELECTRICAL ENGINEERING", selected: false},
    {key: "ENGINEERING MECHANICS PHYSICS AND SCIENCE", value: "ENGINEERING MECHANICS PHYSICS AND SCIENCE", selected: false},
    {key: "ENVIRONMENTAL ENGINEERING", value: "ENVIRONMENTAL ENGINEERING", selected: false},
    {key: "GEOLOGICAL AND GEOPHYSICAL ENGINEERING", value: "GEOLOGICAL AND GEOPHYSICAL ENGINEERING", selected: false},
    {key: "INDUSTRIAL AND MANUFACTURING ENGINEERING", value: "INDUSTRIAL AND MANUFACTURING ENGINEERING", selected: false},
    {key: "MATERIALS ENGINEERING AND MATERIALS SCIENCE", value: "MATERIALS ENGINEERING AND MATERIALS SCIENCE", selected: false},
    {key: "MECHANICAL ENGINEERING", value: "MECHANICAL ENGINEERING", selected: false},
    {key: "METALLURGICAL ENGINEERING", value: "METALLURGICAL ENGINEERING", selected: false},
    {key: "MINING AND MINERAL ENGINEERING", value: "MINING AND MINERAL ENGINEERING", selected: false},
    {key: "NAVAL ARCHITECTURE AND MARINE ENGINEERING", value: "NAVAL ARCHITECTURE AND MARINE ENGINEERING", selected: false},
    {key: "NUCLEAR ENGINEERING", value: "NUCLEAR ENGINEERING", selected: false},
    {key: "PETROLEUM ENGINEERING", value: "PETROLEUM ENGINEERING", selected: false},
    {key: "MISCELLANEOUS ENGINEERING", value: "MISCELLANEOUS ENGINEERING", selected: false},
    {key: "ENGINEERING TECHNOLOGIES", value: "ENGINEERING TECHNOLOGIES", selected: false},
    {key: "ENGINEERING AND INDUSTRIAL MANAGEMENT", value: "ENGINEERING AND INDUSTRIAL MANAGEMENT", selected: false},
    {key: "ELECTRICAL ENGINEERING TECHNOLOGY", value: "ELECTRICAL ENGINEERING TECHNOLOGY", selected: false},
    {key: "INDUSTRIAL PRODUCTION TECHNOLOGIES", value: "INDUSTRIAL PRODUCTION TECHNOLOGIES", selected: false},
    {key: "MECHANICAL ENGINEERING RELATED TECHNOLOGIES", value: "MECHANICAL ENGINEERING RELATED TECHNOLOGIES", selected: false},
    {key: "MISCELLANEOUS ENGINEERING TECHNOLOGIES", value: "MISCELLANEOUS ENGINEERING TECHNOLOGIES", selected: false},
    {key: "MATERIALS SCIENCE", value: "MATERIALS SCIENCE", selected: false},
    {key: "NUTRITION SCIENCES", value: "NUTRITION SCIENCES", selected: false},
    {key: "GENERAL MEDICAL AND HEALTH SERVICES", value: "GENERAL MEDICAL AND HEALTH SERVICES", selected: false},
    {key: "COMMUNICATION DISORDERS SCIENCES AND SERVICES", value: "COMMUNICATION DISORDERS SCIENCES AND SERVICES", selected: false},
    {key: "HEALTH AND MEDICAL ADMINISTRATIVE SERVICES", value: "HEALTH AND MEDICAL ADMINISTRATIVE SERVICES", selected: false},
    {key: "MEDICAL ASSISTING SERVICES", value: "MEDICAL ASSISTING SERVICES", selected: false},
    {key: "MEDICAL TECHNOLOGIES TECHNICIANS", value: "MEDICAL TECHNOLOGIES TECHNICIANS", selected: false},
    {key: "HEALTH AND MEDICAL PREPARATORY PROGRAMS", value: "HEALTH AND MEDICAL PREPARATORY PROGRAMS", selected: false},
    {key: "NURSING", value: "NURSING", selected: false},
    {key: "PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION", value: "PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION", selected: false},
    {key: "TREATMENT THERAPY PROFESSIONS", value: "TREATMENT THERAPY PROFESSIONS", selected: false},
    {key: "COMMUNITY AND PUBLIC HEALTH", value: "COMMUNITY AND PUBLIC HEALTH", selected: false},
    {key: "MISCELLANEOUS HEALTH MEDICAL PROFESSIONS", value: "MISCELLANEOUS HEALTH MEDICAL PROFESSIONS", selected: false},
    {key: "AREA ETHNIC AND CIVILIZATION STUDIES", value: "AREA ETHNIC AND CIVILIZATION STUDIES", selected: false},
    {key: "LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE", value: "LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE", selected: false},
    {key: "FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES", value: "FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES", selected: false},
    {key: "OTHER FOREIGN LANGUAGES", value: "OTHER FOREIGN LANGUAGES", selected: false},
    {key: "ENGLISH LANGUAGE AND LITERATURE", value: "ENGLISH LANGUAGE AND LITERATURE", selected: false},
    {key: "COMPOSITION AND RHETORIC", value: "COMPOSITION AND RHETORIC", selected: false},
    {key: "LIBERAL ARTS", value: "LIBERAL ARTS", selected: false},
    {key: "HUMANITIES", value: "HUMANITIES", selected: false},
    {key: "INTERCULTURAL AND INTERNATIONAL STUDIES", value: "INTERCULTURAL AND INTERNATIONAL STUDIES", selected: false},
    {key: "PHILOSOPHY AND RELIGIOUS STUDIES", value: "PHILOSOPHY AND RELIGIOUS STUDIES", selected: false},
    {key: "THEOLOGY AND RELIGIOUS VOCATIONS", value: "THEOLOGY AND RELIGIOUS VOCATIONS", selected: false},
    {key: "ANTHROPOLOGY AND ARCHEOLOGY", value: "ANTHROPOLOGY AND ARCHEOLOGY", selected: false},
    {key: "ART HISTORY AND CRITICISM", value: "ART HISTORY AND CRITICISM", selected: false},
    {key: "HISTORY", value: "HISTORY", selected: false},
    {key: "UNITED STATES HISTORY", value: "UNITED STATES HISTORY", selected: false},
    {key: "COSMETOLOGY SERVICES AND CULINARY ARTS", value: "COSMETOLOGY SERVICES AND CULINARY ARTS", selected: false},
    {key: "FAMILY AND CONSUMER SCIENCES", value: "FAMILY AND CONSUMER SCIENCES", selected: false},
    {key: "MILITARY TECHNOLOGIES", value: "MILITARY TECHNOLOGIES", selected: false},
    {key: "PHYSICAL FITNESS PARKS RECREATION AND LEISURE", value: "PHYSICAL FITNESS PARKS RECREATION AND LEISURE", selected: false},
    {key: "CONSTRUCTION SERVICES", value: "CONSTRUCTION SERVICES", selected: false},
    {key: "ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION", value: "ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION", selected: false},
    {key: "TRANSPORTATION SCIENCES AND TECHNOLOGIES", value: "TRANSPORTATION SCIENCES AND TECHNOLOGIES", selected: false},
    {key: "MULTI/INTERDISCIPLINARY STUDIES", value: "MULTI/INTERDISCIPLINARY STUDIES", selected: false},
    {key: "COURT REPORTING", value: "COURT REPORTING", selected: false},
    {key: "PRE-LAW AND LEGAL STUDIES", value: "PRE-LAW AND LEGAL STUDIES", selected: false},
    {key: "CRIMINAL JUSTICE AND FIRE PROTECTION", value: "CRIMINAL JUSTICE AND FIRE PROTECTION", selected: false},
    {key: "PUBLIC ADMINISTRATION", value: "PUBLIC ADMINISTRATION", selected: false},
    {key: "PUBLIC POLICY", value: "PUBLIC POLICY", selected: false},
    {key: "PHYSICAL SCIENCES", value: "PHYSICAL SCIENCES", selected: false},
    {key: "ASTRONOMY AND ASTROPHYSICS", value: "ASTRONOMY AND ASTROPHYSICS", selected: false},
    {key: "ATMOSPHERIC SCIENCES AND METEOROLOGY", value: "ATMOSPHERIC SCIENCES AND METEOROLOGY", selected: false},
    {key: "CHEMISTRY", value: "CHEMISTRY", selected: false},
    {key: "GEOLOGY AND EARTH SCIENCE", value: "GEOLOGY AND EARTH SCIENCE", selected: false},
    {key: "GEOSCIENCES", value: "GEOSCIENCES", selected: false},
    {key: "OCEANOGRAPHY", value: "OCEANOGRAPHY", selected: false},
    {key: "PHYSICS", value: "PHYSICS", selected: false},
    {key: "MULTI-DISCIPLINARY OR GENERAL SCIENCE", value: "MULTI-DISCIPLINARY OR GENERAL SCIENCE", selected: false},
    {key: "NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES", value: "NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES", selected: false},
    {key: "PSYCHOLOGY", value: "PSYCHOLOGY", selected: false},
    {key: "EDUCATIONAL PSYCHOLOGY", value: "EDUCATIONAL PSYCHOLOGY", selected: false},
    {key: "CLINICAL PSYCHOLOGY", value: "CLINICAL PSYCHOLOGY", selected: false},
    {key: "COUNSELING PSYCHOLOGY", value: "COUNSELING PSYCHOLOGY", selected: false},
    {key: "INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY", value: "INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY", selected: false},
    {key: "SOCIAL PSYCHOLOGY", value: "SOCIAL PSYCHOLOGY", selected: false},
    {key: "MISCELLANEOUS PSYCHOLOGY", value: "MISCELLANEOUS PSYCHOLOGY", selected: false},
    {key: "HUMAN SERVICES AND COMMUNITY ORGANIZATION", value: "HUMAN SERVICES AND COMMUNITY ORGANIZATION", selected: false},
    {key: "SOCIAL WORK", value: "SOCIAL WORK", selected: false},
    {key: "INTERDISCIPLINARY SOCIAL SCIENCES", value: "INTERDISCIPLINARY SOCIAL SCIENCES", selected: false},
    {key: "GENERAL SOCIAL SCIENCES", value: "GENERAL SOCIAL SCIENCES", selected: false},
    {key: "ECONOMICS", value: "ECONOMICS", selected: false},
    {key: "CRIMINOLOGY", value: "CRIMINOLOGY", selected: false},
    {key: "GEOGRAPHY", value: "GEOGRAPHY", selected: false},
    {key: "INTERNATIONAL RELATIONS", value: "INTERNATIONAL RELATIONS", selected: false},
    {key: "POLITICAL SCIENCE AND GOVERNMENT", value: "POLITICAL SCIENCE AND GOVERNMENT", selected: false},
    {key: "SOCIOLOGY", value: "SOCIOLOGY", selected: false},
    {key: "MISCELLANEOUS SOCIAL SCIENCES", value: "MISCELLANEOUS SOCIAL SCIENCES", selected: false},
]
