export default [
  { selected: false, value: 'English', key: 'English' },
  { selected: false, value: 'German', key: 'Deutsch' },
  { selected: false, value: 'Portuguese', key: 'Português' },
  { selected: false, value: 'Abkhaz', key: 'аҧсуа' },
  { selected: false, value: 'Afar', key: 'Afaraf' },
  { selected: false, value: 'Afrikaans', key: 'Afrikaans' },
  { selected: false, value: 'Akan', key: 'Akan' },
  { selected: false, value: 'Albanian', key: 'Shqip' },
  { selected: false, value: 'Amharic', key: 'አማርኛ' },
  { selected: false, value: 'Arabic', key: 'العربية,' },
  { selected: false, value: 'Aragonese', key: 'Aragonés' },
  { selected: false, value: 'Armenian', key: 'Հայերեն' },
  { selected: false, value: 'Assamese', key: 'অসমীয়া' },
  { selected: false, value: 'Avaric', key: 'авар мацӀ, магӀарул мацӀ' },
  { selected: false, value: 'Avestan', key: 'avesta' },
  { selected: false, value: 'Aymara', key: 'aymar aru' },
  { selected: false, value: 'Azerbaijani', key: 'azərbaycan dili' },
  { selected: false, value: 'Bambara', key: 'bamanankan' },
  { selected: false, value: 'Bashkir', key: 'башҡорт теле' },
  { selected: false, value: 'Basque', key: 'euskara, euskera' },
  { selected: false, value: 'Belarusian', key: 'Беларуская' },
  { selected: false, value: 'Bengali', key: 'বাংলা' },
  { selected: false, value: 'Bihari', key: 'भोजपुरी' },
  { selected: false, value: 'Bislama', key: 'Bislama' },
  { selected: false, value: 'Bosnian', key: 'bosanski jezik' },
  { selected: false, value: 'Breton', key: 'brezhoneg' },
  { selected: false, value: 'Bulgarian', key: 'български език' },
  { selected: false, value: 'Burmese', key: 'ဗမာစာ' },
  { selected: false, value: 'Catalan; Valencian', key: 'Català' },
  { selected: false, value: 'Chamorro', key: 'Chamoru' },
  { selected: false, value: 'Chechen', key: 'нохчийн мотт' },
  {
    selected: false,
    value: 'Chichewa; Chewa; Nyanja',
    key: 'chiCheŵa, chinyanja',
  },
  { selected: false, value: 'Chinese', key: '中文 (Zhōngwén), 汉语, 漢語' },
  { selected: false, value: 'Chuvash', key: 'чӑваш чӗлхи' },
  { selected: false, value: 'Cornish', key: 'Kernewek' },
  { selected: false, value: 'Corsican', key: 'corsu, lingua corsa' },
  { selected: false, value: 'Cree', key: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { selected: false, value: 'Croatian', key: 'hrvatski' },
  { selected: false, value: 'Czech', key: 'česky, čeština' },
  { selected: false, value: 'Danish', key: 'dansk' },
  { selected: false, value: 'Divehi; Dhivehi; Maldivian;', key: 'ދިވެހި,' },
  { selected: false, value: 'Dutch', key: 'Nederlands, Vlaams' },
  { selected: false, value: 'Esperanto', key: 'Esperanto' },
  { selected: false, value: 'Estonian', key: 'eesti, eesti keel' },
  { selected: false, value: 'Ewe', key: 'Eʋegbe' },
  { selected: false, value: 'Faroese', key: 'føroyskt' },
  { selected: false, value: 'Fijian', key: 'vosa Vakaviti' },
  { selected: false, value: 'Finnish', key: 'suomi, suomen kieli' },
  { selected: false, value: 'French', key: 'français, langue française' },
  {
    selected: false,
    value: 'Fula; Fulah; Pulaar; Pular',
    key: 'Fulfulde, Pulaar, Pular',
  },
  { selected: false, value: 'Galician', key: 'Galego' },
  { selected: false, value: 'Georgian', key: 'ქართული' },
  { selected: false, value: 'Greek, Modern', key: 'Ελληνικά' },
  { selected: false, value: 'Guaraní', key: 'Avañeẽ' },
  { selected: false, value: 'Gujarati', key: 'ગુજરાતી' },
  { selected: false, value: 'Haitian; Haitian Creole', key: 'Kreyòl ayisyen' },
  { selected: false, value: 'Hausa', key: 'Hausa, هَوُسَ' },
  { selected: false, value: 'Hebrew', key: 'עברית,' },
  { selected: false, value: 'Herero', key: 'Otjiherero' },
  { selected: false, value: 'Hindi', key: 'हिन्दी, हिंदी' },
  { selected: false, value: 'Hiri Motu', key: 'Hiri Motu' },
  { selected: false, value: 'Hungarian', key: 'Magyar' },
  { selected: false, value: 'Interlingua', key: 'Interlingua' },
  { selected: false, value: 'Indonesian', key: 'Bahasa Indonesia' },
  {
    selected: false,
    value: 'Interlingue',
    key: 'Originally called Occidental; then Interlingue after WWII',
  },
  { selected: false, value: 'Irish', key: 'Gaeilge' },
  { selected: false, value: 'Igbo', key: 'Asụsụ Igbo' },
  { selected: false, value: 'Inupiaq', key: 'Iñupiaq, Iñupiatun' },
  { selected: false, value: 'Ido', key: 'Ido' },
  { selected: false, value: 'Icelandic', key: 'Íslenska' },
  { selected: false, value: 'Italian', key: 'Italiano' },
  { selected: false, value: 'Inuktitut', key: 'ᐃᓄᒃᑎᑐᑦ' },
  { selected: false, value: 'Japanese', key: '日本語 (にほんご／にっぽんご)' },
  { selected: false, value: 'Javanese', key: 'basa Jawa' },
  {
    selected: false,
    value: 'Kalaallisut, Greenlandic',
    key: 'kalaallisut, kalaallit oqaasii',
  },
  { selected: false, value: 'Kannada', key: 'ಕನ್ನಡ' },
  { selected: false, value: 'Kanuri', key: 'Kanuri' },
  { selected: false, value: 'Kashmiri', key: 'कश्मीरी, كشميري‎' },
  { selected: false, value: 'Kazakh', key: 'Қазақ тілі' },
  { selected: false, value: 'Khmer', key: 'ភាសាខ្មែរ' },
  { selected: false, value: 'Kikuyu, Gikuyu', key: 'Gĩkũyũ' },
  { selected: false, value: 'Kinyarwanda', key: 'Ikinyarwanda' },
  { selected: false, value: 'Kirghiz, Kyrgyz', key: 'кыргыз тили' },
  { selected: false, value: 'Komi', key: 'коми кыв' },
  { selected: false, value: 'Kongo', key: 'KiKongo' },
  { selected: false, value: 'Korean', key: '한국어 (韓國語), 조선말 (朝鮮語)' },
  { selected: false, value: 'Kurdish', key: 'Kurdî, كوردی‎' },
  { selected: false, value: 'Kwanyama, Kuanyama', key: 'Kuanyama' },
  { selected: false, value: 'Latin', key: 'latine, lingua latina' },
  {
    selected: false,
    value: 'Luxembourgish, Letzeburgesch',
    key: 'Lëtzebuergesch',
  },
  { selected: false, value: 'Luganda', key: 'Luganda' },
  {
    selected: false,
    value: 'Limburgish, Limburgan, Limburger',
    key: 'Limburgs',
  },
  { selected: false, value: 'Lingala', key: 'Lingála' },
  { selected: false, value: 'Lao', key: 'ພາສາລາວ' },
  { selected: false, value: 'Lithuanian', key: 'lietuvių kalba' },
  { selected: false, value: 'Luba-Katanga', key: '' },
  { selected: false, value: 'Latvian', key: 'latviešu valoda' },
  { selected: false, value: 'Manx', key: 'Gaelg, Gailck' },
  { selected: false, value: 'Macedonian', key: 'македонски јазик' },
  { selected: false, value: 'Malagasy', key: 'Malagasy fiteny' },
  { selected: false, value: 'Malay', key: 'bahasa Melayu, بهاس ملايو‎' },
  { selected: false, value: 'Malayalam', key: 'മലയാളം' },
  { selected: false, value: 'Maltese', key: 'Malti' },
  { selected: false, value: 'Māori', key: 'te reo Māori' },
  { selected: false, value: 'Marathi (Marāṭhī)', key: 'मराठी' },
  { selected: false, value: 'Marshallese', key: 'Kajin M̧ajeļ' },
  { selected: false, value: 'Mongolian', key: 'монгол' },
  { selected: false, value: 'Nauru', key: 'Ekakairũ Naoero' },
  { selected: false, value: 'Navajo, Navaho', key: 'Diné bizaad, Dinékʼehǰí' },
  { selected: false, value: 'Norwegian Bokmål', key: 'Norsk bokmål' },
  { selected: false, value: 'North Ndebele', key: 'northIsiNdebele' },
  { selected: false, value: 'Nepali', key: 'नेपाली' },
  { selected: false, value: 'Ndonga', key: 'Owambo' },
  { selected: false, value: 'Norwegian Nynorsk', key: 'Norsk nynorsk' },
  { selected: false, value: 'Norwegian', key: 'Norsk' },
  { selected: false, value: 'Nuosu', key: 'ꆈꌠ꒿ Nuosuhxop' },
  { selected: false, value: 'South Ndebele', key: 'isiNdebele' },
  { selected: false, value: 'Occitan', key: 'Occitan' },
  { selected: false, value: 'Ojibwe, Ojibwa', key: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  {
    selected: false,
    value:
      'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
    key: 'ѩзыкъ словѣньскъ',
  },
  { selected: false, value: 'Oromo', key: 'Afaan Oromoo' },
  { selected: false, value: 'Oriya', key: 'ଓଡ଼ିଆ' },
  { selected: false, value: 'Ossetian, Ossetic', key: 'ирон æвзаг' },
  { selected: false, value: 'Panjabi, Punjabi', key: 'ਪੰਜਾਬੀ, پنجابی‎' },
  { selected: false, value: 'Pāli', key: 'पाऴि' },
  { selected: false, value: 'Persian', key: 'فارسی,' },
  { selected: false, value: 'Polish', key: 'polski' },
  { selected: false, value: 'Pashto, Pushto', key: 'پښتو,' },
  { selected: false, value: 'Quechua', key: 'Runa Simi, Kichwa' },
  { selected: false, value: 'Romansh', key: 'rumantsch grischun' },
  { selected: false, value: 'Kirundi', key: 'kiRundi' },
  { selected: false, value: 'Romanian, Moldavian, Moldovan', key: 'română' },
  { selected: false, value: 'Russian', key: 'русский язык' },
  { selected: false, value: 'Sanskrit (Saṁskṛta)', key: 'संस्कृतम्' },
  { selected: false, value: 'Sardinian', key: 'sardu' },
  { selected: false, value: 'Sindhi', key: 'सिन्धी, سنڌي، سندھی‎' },
  { selected: false, value: 'Northern Sami', key: 'Davvisámegiella' },
  { selected: false, value: 'Samoan', key: 'gagana faa Samoa' },
  { selected: false, value: 'Sango', key: 'yângâ tî sängö' },
  { selected: false, value: 'Serbian', key: 'српски језик' },
  { selected: false, value: 'Scottish Gaelic; Gaelic', key: 'Gàidhlig' },
  { selected: false, value: 'Shona', key: 'chiShona' },
  { selected: false, value: 'Sinhala, Sinhalese', key: 'සිංහල' },
  { selected: false, value: 'Slovak', key: 'slovenčina' },
  { selected: false, value: 'Slovene', key: 'slovenščina' },
  { selected: false, value: 'Somali', key: 'Soomaaliga, af Soomaali' },
  { selected: false, value: 'Southern Sotho', key: 'Sesotho' },
  { selected: false, value: 'Spanish; Castilian', key: 'español, castellano' },
  { selected: false, value: 'Sundanese', key: 'Basa Sunda' },
  { selected: false, value: 'Swahili', key: 'Kiswahili' },
  { selected: false, value: 'Swati', key: 'SiSwati' },
  { selected: false, value: 'Swedish', key: 'svenska' },
  { selected: false, value: 'Tamil', key: 'தமிழ்' },
  { selected: false, value: 'Telugu', key: 'తెలుగు' },
  { selected: false, value: 'Tajik', key: 'тоҷикӣ, toğikī, تاجیکی‎' },
  { selected: false, value: 'Thai', key: 'ไทย' },
  { selected: false, value: 'Tigrinya', key: 'ትግርኛ' },
  {
    selected: false,
    value: 'Tibetan Standard, Tibetan, Central',
    key: 'བོད་ཡིག',
  },
  { selected: false, value: 'Turkmen', key: 'Türkmen, Түркмен' },
  { selected: false, value: 'Tagalog', key: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔' },
  { selected: false, value: 'Tswana', key: 'Setswana' },
  { selected: false, value: 'Tonga (Tonga Islands)', key: 'faka Tonga' },
  { selected: false, value: 'Turkish', key: 'Türkçe' },
  { selected: false, value: 'Tsonga', key: 'Xitsonga' },
  { selected: false, value: 'Tatar', key: 'татарча, tatarça, تاتارچا‎' },
  { selected: false, value: 'Twi', key: 'Twi' },
  { selected: false, value: 'Tahitian', key: 'Reo Tahiti' },
  { selected: false, value: 'Uighur, Uyghur', key: 'Uyƣurqə, ئۇيغۇرچە‎' },
  { selected: false, value: 'Ukrainian', key: 'українська' },
  { selected: false, value: 'Urdu', key: 'اردو,' },
  { selected: false, value: 'Uzbek', key: 'zbek, Ўзбек, أۇزبېك‎' },
  { selected: false, value: 'Venda', key: 'Tshivenḓa' },
  { selected: false, value: 'Vietvaluese', key: 'keyTếng Việt' },
  { selected: false, value: 'Volapük', key: 'Volapük' },
  { selected: false, value: 'Walloon', key: 'Walon' },
  { selected: false, value: 'Welsh', key: 'Cymraeg' },
  { selected: false, value: 'Wolof', key: 'Wollof' },
  { selected: false, value: 'Western Frisian', key: 'Frysk' },
  { selected: false, value: 'Xhosa', key: 'isiXhosa' },
  { selected: false, value: 'Yiddish', key: 'ייִדיש,' },
  { selected: false, value: 'Yoruba', key: 'Yorùbá' },
  { selected: false, value: 'Zhuang, Chuang', key: 'Saɯ cueŋƅ, Saw cuengh' },
];
