export default [
        {key: "accountant", value: "accountant", selected: false},
        {key: "actor", value: "actor", selected: false},
        {key: "actuary", value: "actuary", selected: false},
        {key: "adhesive bonding machine tender", value: "adhesive bonding machine tender", selected: false},
        {key: "adjudicator", value: "adjudicator", selected: false},
        {key: "administrative assistant", value: "administrative assistant", selected: false},
        {key: "administrative services manager", value: "administrative services manager", selected: false},
        {key: "adult education teacher", value: "adult education teacher", selected: false},
        {key: "advertising manager", value: "advertising manager", selected: false},
        {key: "advertising sales agent", value: "advertising sales agent", selected: false},
        {key: "aerobics instructor", value: "aerobics instructor", selected: false},
        {key: "aerospace engineer", value: "aerospace engineer", selected: false},
        {key: "aerospace engineering technician", value: "aerospace engineering technician", selected: false},
        {key: "agent", value: "agent", selected: false},
        {key: "agricultural engineer", value: "agricultural engineer", selected: false},
        {key: "agricultural equipment operator", value: "agricultural equipment operator", selected: false},
        {key: "agricultural grader", value: "agricultural grader", selected: false},
        {key: "agricultural inspector", value: "agricultural inspector", selected: false},
        {key: "agricultural manager", value: "agricultural manager", selected: false},
        {key: "agricultural sciences teacher", value: "agricultural sciences teacher", selected: false},
        {key: "agricultural sorter", value: "agricultural sorter", selected: false},
        {key: "agricultural technician", value: "agricultural technician", selected: false},
        {key: "agricultural worker", value: "agricultural worker", selected: false},
        {key: "air conditioning installer", value: "air conditioning installer", selected: false},
        {key: "air conditioning mechanic", value: "air conditioning mechanic", selected: false},
        {key: "air traffic controller", value: "air traffic controller", selected: false},
        {key: "aircraft cargo handling supervisor", value: "aircraft cargo handling supervisor", selected: false},
        {key: "aircraft mechanic", value: "aircraft mechanic", selected: false},
        {key: "aircraft service technician", value: "aircraft service technician", selected: false},
        {key: "airline copilot", value: "airline copilot", selected: false},
        {key: "airline pilot", value: "airline pilot", selected: false},
        {key: "ambulance dispatcher", value: "ambulance dispatcher", selected: false},
        {key: "ambulance driver", value: "ambulance driver", selected: false},
        {key: "amusement machine servicer", value: "amusement machine servicer", selected: false},
        {key: "anesthesiologist", value: "anesthesiologist", selected: false},
        {key: "animal breeder", value: "animal breeder", selected: false},
        {key: "animal control worker", value: "animal control worker", selected: false},
        {key: "animal scientist", value: "animal scientist", selected: false},
        {key: "animal trainer", value: "animal trainer", selected: false},
        {key: "animator", value: "animator", selected: false},
        {key: "answering service operator", value: "answering service operator", selected: false},
        {key: "anthropologist", value: "anthropologist", selected: false},
        {key: "apparel patternmaker", value: "apparel patternmaker", selected: false},
        {key: "apparel worker", value: "apparel worker", selected: false},
        {key: "arbitrator", value: "arbitrator", selected: false},
        {key: "archeologist", value: "archeologist", selected: false},
        {key: "architect", value: "architect", selected: false},
        {key: "architectural drafter", value: "architectural drafter", selected: false},
        {key: "architectural manager", value: "architectural manager", selected: false},
        {key: "archivist", value: "archivist", selected: false},
        {key: "art director", value: "art director", selected: false},
        {key: "art teacher", value: "art teacher", selected: false},
        {key: "artist", value: "artist", selected: false},
        {key: "assembler", value: "assembler", selected: false},
        {key: "astronomer", value: "astronomer", selected: false},
        {key: "athlete", value: "athlete", selected: false},
        {key: "athletic trainer", value: "athletic trainer", selected: false},
        {key: "ATM machine repairer", value: "ATM machine repairer", selected: false},
        {key: "atmospheric scientist", value: "atmospheric scientist", selected: false},
        {key: "attendant", value: "attendant", selected: false},
        {key: "audio and video equipment technician", value: "audio and video equipment technician", selected: false},
        {key: "audio-visual and multimedia collections specialist", value: "audio-visual and multimedia collections specialist", selected: false},
        {key: "audiologist", value: "audiologist", selected: false},
        {key: "auditor", value: "auditor", selected: false},
        {key: "author", value: "author", selected: false},
        {key: "auto damage insurance appraiser", value: "auto damage insurance appraiser", selected: false},
        {key: "automotive and watercraft service attendant", value: "automotive and watercraft service attendant", selected: false},
        {key: "automotive glass installer", value: "automotive glass installer", selected: false},
        {key: "automotive mechanic", value: "automotive mechanic", selected: false},
        {key: "avionics technician", value: "avionics technician", selected: false},
        {key: "baggage porter", value: "baggage porter", selected: false},
        {key: "bailiff", value: "bailiff", selected: false},
        {key: "baker", value: "baker", selected: false},
        {key: "barback", value: "barback", selected: false},
        {key: "barber", value: "barber", selected: false},
        {key: "bartender", value: "bartender", selected: false},
        {key: "basic education teacher", value: "basic education teacher", selected: false},
        {key: "behavioral disorder counselor", value: "behavioral disorder counselor", selected: false},
        {key: "bellhop", value: "bellhop", selected: false},
        {key: "bench carpenter", value: "bench carpenter", selected: false},
        {key: "bicycle repairer", value: "bicycle repairer", selected: false},
        {key: "bill and account collector", value: "bill and account collector", selected: false},
        {key: "billing and posting clerk", value: "billing and posting clerk", selected: false},
        {key: "biochemist", value: "biochemist", selected: false},
        {key: "biological technician", value: "biological technician", selected: false},
        {key: "biomedical engineer", value: "biomedical engineer", selected: false},
        {key: "biophysicist", value: "biophysicist", selected: false},
        {key: "blaster", value: "blaster", selected: false},
        {key: "blending machine operator", value: "blending machine operator", selected: false},
        {key: "blockmason", value: "blockmason", selected: false},
        {key: "boiler operator", value: "boiler operator", selected: false},
        {key: "boilermaker", value: "boilermaker", selected: false},
        {key: "bookkeeper", value: "bookkeeper", selected: false},
        {key: "boring machine tool tender", value: "boring machine tool tender", selected: false},
        {key: "brazer", value: "brazer", selected: false},
        {key: "brickmason", value: "brickmason", selected: false},
        {key: "bridge and lock tender", value: "bridge and lock tender", selected: false},
        {key: "broadcast news analyst", value: "broadcast news analyst", selected: false},
        {key: "broadcast technician", value: "broadcast technician", selected: false},
        {key: "brokerage clerk", value: "brokerage clerk", selected: false},
        {key: "budget analyst", value: "budget analyst", selected: false},
        {key: "building inspector", value: "building inspector", selected: false},
        {key: "bus mechanic", value: "bus mechanic", selected: false},
        {key: "butcher", value: "butcher", selected: false},
        {key: "buyer", value: "buyer", selected: false},
        {key: "cabinetmaker", value: "cabinetmaker", selected: false},
        {key: "cafeteria attendant", value: "cafeteria attendant", selected: false},
        {key: "cafeteria cook", value: "cafeteria cook", selected: false},
        {key: "camera operator", value: "camera operator", selected: false},
        {key: "camera repairer", value: "camera repairer", selected: false},
        {key: "cardiovascular technician", value: "cardiovascular technician", selected: false},
        {key: "cargo agent", value: "cargo agent", selected: false},
        {key: "carpenter", value: "carpenter", selected: false},
        {key: "carpet installer", value: "carpet installer", selected: false},
        {key: "cartographer", value: "cartographer", selected: false},
        {key: "cashier", value: "cashier", selected: false},
        {key: "caster", value: "caster", selected: false},
        {key: "ceiling tile installer", value: "ceiling tile installer", selected: false},
        {key: "cellular equipment installer", value: "cellular equipment installer", selected: false},
        {key: "cement mason", value: "cement mason", selected: false},
        {key: "channeling machine operator", value: "channeling machine operator", selected: false},
        {key: "chauffeur", value: "chauffeur", selected: false},
        {key: "checker", value: "checker", selected: false},
        {key: "chef", value: "chef", selected: false},
        {key: "chemical engineer", value: "chemical engineer", selected: false},
        {key: "chemical plant operator", value: "chemical plant operator", selected: false},
        {key: "chemist", value: "chemist", selected: false},
        {key: "chemistry teacher", value: "chemistry teacher", selected: false},
        {key: "chief executive", value: "chief executive", selected: false},
        {key: "child social worker", value: "child social worker", selected: false},
        {key: "childcare worker", value: "childcare worker", selected: false},
        {key: "chiropractor", value: "chiropractor", selected: false},
        {key: "choreographer", value: "choreographer", selected: false},
        {key: "civil drafter", value: "civil drafter", selected: false},
        {key: "civil engineer", value: "civil engineer", selected: false},
        {key: "civil engineering technician", value: "civil engineering technician", selected: false},
        {key: "claims adjuster", value: "claims adjuster", selected: false},
        {key: "claims examiner", value: "claims examiner", selected: false},
        {key: "claims investigator", value: "claims investigator", selected: false},
        {key: "cleaner", value: "cleaner", selected: false},
        {key: "clinical laboratory technician", value: "clinical laboratory technician", selected: false},
        {key: "clinical laboratory technologist", value: "clinical laboratory technologist", selected: false},
        {key: "clinical psychologist", value: "clinical psychologist", selected: false},
        {key: "coating worker", value: "coating worker", selected: false},
        {key: "coatroom attendant", value: "coatroom attendant", selected: false},
        {key: "coil finisher", value: "coil finisher", selected: false},
        {key: "coil taper", value: "coil taper", selected: false},
        {key: "coil winder", value: "coil winder", selected: false},
        {key: "coin machine servicer", value: "coin machine servicer", selected: false},
        {key: "commercial diver", value: "commercial diver", selected: false},
        {key: "commercial pilot", value: "commercial pilot", selected: false},
        {key: "commodities sales agent", value: "commodities sales agent", selected: false},
        {key: "communications equipment operator", value: "communications equipment operator", selected: false},
        {key: "communications teacher", value: "communications teacher", selected: false},
        {key: "community association manager", value: "community association manager", selected: false},
        {key: "community service manager", value: "community service manager", selected: false},
        {key: "compensation and benefits manager", value: "compensation and benefits manager", selected: false},
        {key: "compliance officer", value: "compliance officer", selected: false},
        {key: "composer", value: "composer", selected: false},
        {key: "computer hardware engineer", value: "computer hardware engineer", selected: false},
        {key: "computer network architect", value: "computer network architect", selected: false},
        {key: "computer operator", value: "computer operator", selected: false},
        {key: "computer programmer", value: "computer programmer", selected: false},
        {key: "computer science teacher", value: "computer science teacher", selected: false},
        {key: "computer support specialist", value: "computer support specialist", selected: false},
        {key: "computer systems administrator", value: "computer systems administrator", selected: false},
        {key: "computer systems analyst", value: "computer systems analyst", selected: false},
        {key: "concierge", value: "concierge", selected: false},
        {key: "conciliator", value: "conciliator", selected: false},
        {key: "concrete finisher", value: "concrete finisher", selected: false},
        {key: "conservation science teacher", value: "conservation science teacher", selected: false},
        {key: "conservation scientist", value: "conservation scientist", selected: false},
        {key: "conservation worker", value: "conservation worker", selected: false},
        {key: "conservator", value: "conservator", selected: false},
        {key: "construction inspector", value: "construction inspector", selected: false},
        {key: "construction manager", value: "construction manager", selected: false},
        {key: "construction painter", value: "construction painter", selected: false},
        {key: "construction worker", value: "construction worker", selected: false},
        {key: "continuous mining machine operator", value: "continuous mining machine operator", selected: false},
        {key: "convention planner", value: "convention planner", selected: false},
        {key: "conveyor operator", value: "conveyor operator", selected: false},
        {key: "cook", value: "cook", selected: false},
        {key: "cooling equipment operator", value: "cooling equipment operator", selected: false},
        {key: "copy marker", value: "copy marker", selected: false},
        {key: "correctional officer", value: "correctional officer", selected: false},
        {key: "correctional treatment specialist", value: "correctional treatment specialist", selected: false},
        {key: "correspondence clerk", value: "correspondence clerk", selected: false},
        {key: "correspondent", value: "correspondent", selected: false},
        {key: "cosmetologist", value: "cosmetologist", selected: false},
        {key: "cost estimator", value: "cost estimator", selected: false},
        {key: "costume attendant", value: "costume attendant", selected: false},
        {key: "counseling psychologist", value: "counseling psychologist", selected: false},
        {key: "counselor", value: "counselor", selected: false},
        {key: "courier", value: "courier", selected: false},
        {key: "court reporter", value: "court reporter", selected: false},
        {key: "craft artist", value: "craft artist", selected: false},
        {key: "crane operator", value: "crane operator", selected: false},
        {key: "credit analyst", value: "credit analyst", selected: false},
        {key: "credit checker", value: "credit checker", selected: false},
        {key: "credit counselor", value: "credit counselor", selected: false},
        {key: "criminal investigator", value: "criminal investigator", selected: false},
        {key: "criminal justice teacher", value: "criminal justice teacher", selected: false},
        {key: "crossing guard", value: "crossing guard", selected: false},
        {key: "curator", value: "curator", selected: false},
        {key: "custom sewer", value: "custom sewer", selected: false},
        {key: "customer service representative", value: "customer service representative", selected: false},
        {key: "cutter", value: "cutter", selected: false},
        {key: "cutting machine operator", value: "cutting machine operator", selected: false},
        {key: "dancer", value: "dancer", selected: false},
        {key: "data entry keyer", value: "data entry keyer", selected: false},
        {key: "database administrator", value: "database administrator", selected: false},
        {key: "decorating worker", value: "decorating worker", selected: false},
        {key: "delivery services driver", value: "delivery services driver", selected: false},
        {key: "demonstrator", value: "demonstrator", selected: false},
        {key: "dental assistant", value: "dental assistant", selected: false},
        {key: "dental hygienist", value: "dental hygienist", selected: false},
        {key: "dental laboratory technician", value: "dental laboratory technician", selected: false},
        {key: "dentist", value: "dentist", selected: false},
        {key: "derrick operator", value: "derrick operator", selected: false},
        {key: "designer", value: "designer", selected: false},
        {key: "desktop publisher", value: "desktop publisher", selected: false},
        {key: "detective", value: "detective", selected: false},
        {key: "diagnostic medical sonographer", value: "diagnostic medical sonographer", selected: false},
        {key: "die maker", value: "die maker", selected: false},
        {key: "diesel engine specialist", value: "diesel engine specialist", selected: false},
        {key: "dietetic technician", value: "dietetic technician", selected: false},
        {key: "dietitian", value: "dietitian", selected: false},
        {key: "dinkey operator", value: "dinkey operator", selected: false},
        {key: "director", value: "director", selected: false},
        {key: "dishwasher", value: "dishwasher", selected: false},
        {key: "dispatcher", value: "dispatcher", selected: false},
        {key: "door-to-door sales worker", value: "door-to-door sales worker", selected: false},
        {key: "drafter", value: "drafter", selected: false},
        {key: "dragline operator", value: "dragline operator", selected: false},
        {key: "drama teacher", value: "drama teacher", selected: false},
        {key: "dredge operator", value: "dredge operator", selected: false},
        {key: "dressing room attendant", value: "dressing room attendant", selected: false},
        {key: "dressmaker", value: "dressmaker", selected: false},
        {key: "drier operator", value: "drier operator", selected: false},
        {key: "drilling machine tool operator", value: "drilling machine tool operator", selected: false},
        {key: "dry-cleaning worker", value: "dry-cleaning worker", selected: false},
        {key: "drywall installer", value: "drywall installer", selected: false},
        {key: "dyeing machine operator", value: "dyeing machine operator", selected: false},
        {key: "earth driller", value: "earth driller", selected: false},
        {key: "economics teacher", value: "economics teacher", selected: false},
        {key: "economist", value: "economist", selected: false},
        {key: "editor", value: "editor", selected: false},
        {key: "education administrator", value: "education administrator", selected: false},
        {key: "electric motor repairer", value: "electric motor repairer", selected: false},
        {key: "electrical electronics drafter", value: "electrical electronics drafter", selected: false},
        {key: "electrical engineer", value: "electrical engineer", selected: false},
        {key: "electrical equipment assembler", value: "electrical equipment assembler", selected: false},
        {key: "electrical installer", value: "electrical installer", selected: false},
        {key: "electrical power-line installer", value: "electrical power-line installer", selected: false},
        {key: "electrician", value: "electrician", selected: false},
        {key: "electro-mechanical technician", value: "electro-mechanical technician", selected: false},
        {key: "elementary school teacher", value: "elementary school teacher", selected: false},
        {key: "elevator installer", value: "elevator installer", selected: false},
        {key: "elevator repairer", value: "elevator repairer", selected: false},
        {key: "embalmer", value: "embalmer", selected: false},
        {key: "emergency management director", value: "emergency management director", selected: false},
        {key: "emergency medical technician", value: "emergency medical technician", selected: false},
        {key: "engine assembler", value: "engine assembler", selected: false},
        {key: "engineer", value: "engineer", selected: false},
        {key: "engineering manager", value: "engineering manager", selected: false},
        {key: "engineering teacher", value: "engineering teacher", selected: false},
        {key: "english language teacher", value: "english language teacher", selected: false},
        {key: "engraver", value: "engraver", selected: false},
        {key: "entertainment attendant", value: "entertainment attendant", selected: false},
        {key: "environmental engineer", value: "environmental engineer", selected: false},
        {key: "environmental science teacher", value: "environmental science teacher", selected: false},
        {key: "environmental scientist", value: "environmental scientist", selected: false},
        {key: "epidemiologist", value: "epidemiologist", selected: false},
        {key: "escort", value: "escort", selected: false},
        {key: "etcher", value: "etcher", selected: false},
        {key: "event planner", value: "event planner", selected: false},
        {key: "excavating operator", value: "excavating operator", selected: false},
        {key: "executive administrative assistant", value: "executive administrative assistant", selected: false},
        {key: "executive secretary", value: "executive secretary", selected: false},
        {key: "exhibit designer", value: "exhibit designer", selected: false},
        {key: "expediting clerk", value: "expediting clerk", selected: false},
        {key: "explosives worker", value: "explosives worker", selected: false},
        {key: "extraction worker", value: "extraction worker", selected: false},
        {key: "fabric mender", value: "fabric mender", selected: false},
        {key: "fabric patternmaker", value: "fabric patternmaker", selected: false},
        {key: "fabricator", value: "fabricator", selected: false},
        {key: "faller", value: "faller", selected: false},
        {key: "family practitioner", value: "family practitioner", selected: false},
        {key: "family social worker", value: "family social worker", selected: false},
        {key: "family therapist", value: "family therapist", selected: false},
        {key: "farm advisor", value: "farm advisor", selected: false},
        {key: "farm equipment mechanic", value: "farm equipment mechanic", selected: false},
        {key: "farm labor contractor", value: "farm labor contractor", selected: false},
        {key: "farmer", value: "farmer", selected: false},
        {key: "farmworker", value: "farmworker", selected: false},
        {key: "fashion designer", value: "fashion designer", selected: false},
        {key: "fast food cook", value: "fast food cook", selected: false},
        {key: "fence erector", value: "fence erector", selected: false},
        {key: "fiberglass fabricator", value: "fiberglass fabricator", selected: false},
        {key: "fiberglass laminator", value: "fiberglass laminator", selected: false},
        {key: "file clerk", value: "file clerk", selected: false},
        {key: "filling machine operator", value: "filling machine operator", selected: false},
        {key: "film and video editor", value: "film and video editor", selected: false},
        {key: "financial analyst", value: "financial analyst", selected: false},
        {key: "financial examiner", value: "financial examiner", selected: false},
        {key: "financial manager", value: "financial manager", selected: false},
        {key: "financial services sales agent", value: "financial services sales agent", selected: false},
        {key: "fine artist", value: "fine artist", selected: false},
        {key: "fire alarm system installer", value: "fire alarm system installer", selected: false},
        {key: "fire dispatcher", value: "fire dispatcher", selected: false},
        {key: "fire inspector", value: "fire inspector", selected: false},
        {key: "fire investigator", value: "fire investigator", selected: false},
        {key: "firefighter", value: "firefighter", selected: false},
        {key: "fish and game warden", value: "fish and game warden", selected: false},
        {key: "fish cutter", value: "fish cutter", selected: false},
        {key: "fish trimmer", value: "fish trimmer", selected: false},
        {key: "fisher", value: "fisher", selected: false},
        {key: "fitness studies teacher", value: "fitness studies teacher", selected: false},
        {key: "fitness trainer", value: "fitness trainer", selected: false},
        {key: "flight attendant", value: "flight attendant", selected: false},
        {key: "floor finisher", value: "floor finisher", selected: false},
        {key: "floor layer", value: "floor layer", selected: false},
        {key: "floor sander", value: "floor sander", selected: false},
        {key: "floral designer", value: "floral designer", selected: false},
        {key: "food batchmaker", value: "food batchmaker", selected: false},
        {key: "food cooking machine operator", value: "food cooking machine operator", selected: false},
        {key: "food preparation worker", value: "food preparation worker", selected: false},
        {key: "food science technician", value: "food science technician", selected: false},
        {key: "food scientist", value: "food scientist", selected: false},
        {key: "food server", value: "food server", selected: false},
        {key: "food service manager", value: "food service manager", selected: false},
        {key: "food technologist", value: "food technologist", selected: false},
        {key: "foreign language teacher", value: "foreign language teacher", selected: false},
        {key: "foreign literature teacher", value: "foreign literature teacher", selected: false},
        {key: "forensic science technician", value: "forensic science technician", selected: false},
        {key: "forest fire inspector", value: "forest fire inspector", selected: false},
        {key: "forest fire prevention specialist", value: "forest fire prevention specialist", selected: false},
        {key: "forest worker", value: "forest worker", selected: false},
        {key: "forester", value: "forester", selected: false},
        {key: "forestry teacher", value: "forestry teacher", selected: false},
        {key: "forging machine setter", value: "forging machine setter", selected: false},
        {key: "foundry coremaker", value: "foundry coremaker", selected: false},
        {key: "freight agent", value: "freight agent", selected: false},
        {key: "freight mover", value: "freight mover", selected: false},
        {key: "fundraising manager", value: "fundraising manager", selected: false},
        {key: "funeral attendant", value: "funeral attendant", selected: false},
        {key: "funeral director", value: "funeral director", selected: false},
        {key: "funeral service manager", value: "funeral service manager", selected: false},
        {key: "furnace operator", value: "furnace operator", selected: false},
        {key: "furnishings worker", value: "furnishings worker", selected: false},
        {key: "furniture finisher", value: "furniture finisher", selected: false},
        {key: "gaming booth cashier", value: "gaming booth cashier", selected: false},
        {key: "gaming cage worker", value: "gaming cage worker", selected: false},
        {key: "gaming change person", value: "gaming change person", selected: false},
        {key: "gaming dealer", value: "gaming dealer", selected: false},
        {key: "gaming investigator", value: "gaming investigator", selected: false},
        {key: "gaming manager", value: "gaming manager", selected: false},
        {key: "gaming surveillance officer", value: "gaming surveillance officer", selected: false},
        {key: "garment mender", value: "garment mender", selected: false},
        {key: "garment presser", value: "garment presser", selected: false},
        {key: "gas compressor", value: "gas compressor", selected: false},
        {key: "gas plant operator", value: "gas plant operator", selected: false},
        {key: "gas pumping station operator", value: "gas pumping station operator", selected: false},
        {key: "general manager", value: "general manager", selected: false},
        {key: "general practitioner", value: "general practitioner", selected: false},
        {key: "geographer", value: "geographer", selected: false},
        {key: "geography teacher", value: "geography teacher", selected: false},
        {key: "geological engineer", value: "geological engineer", selected: false},
        {key: "geological technician", value: "geological technician", selected: false},
        {key: "geoscientist", value: "geoscientist", selected: false},
        {key: "glazier", value: "glazier", selected: false},
        {key: "government program eligibility interviewer", value: "government program eligibility interviewer", selected: false},
        {key: "graduate teaching assistant", value: "graduate teaching assistant", selected: false},
        {key: "graphic designer", value: "graphic designer", selected: false},
        {key: "groundskeeper", value: "groundskeeper", selected: false},
        {key: "groundskeeping worker", value: "groundskeeping worker", selected: false},
        {key: "gynecologist", value: "gynecologist", selected: false},
        {key: "hairdresser", value: "hairdresser", selected: false},
        {key: "hairstylist", value: "hairstylist", selected: false},
        {key: "hand grinding worker", value: "hand grinding worker", selected: false},
        {key: "hand laborer", value: "hand laborer", selected: false},
        {key: "hand packager", value: "hand packager", selected: false},
        {key: "hand packer", value: "hand packer", selected: false},
        {key: "hand polishing worker", value: "hand polishing worker", selected: false},
        {key: "hand sewer", value: "hand sewer", selected: false},
        {key: "hazardous materials removal worker", value: "hazardous materials removal worker", selected: false},
        {key: "head cook", value: "head cook", selected: false},
        {key: "health and safety engineer", value: "health and safety engineer", selected: false},
        {key: "health educator", value: "health educator", selected: false},
        {key: "health information technician", value: "health information technician", selected: false},
        {key: "health services manager", value: "health services manager", selected: false},
        {key: "health specialties teacher", value: "health specialties teacher", selected: false},
        {key: "healthcare social worker", value: "healthcare social worker", selected: false},
        {key: "hearing officer", value: "hearing officer", selected: false},
        {key: "heat treating equipment setter", value: "heat treating equipment setter", selected: false},
        {key: "heating installer", value: "heating installer", selected: false},
        {key: "heating mechanic", value: "heating mechanic", selected: false},
        {key: "heavy truck driver", value: "heavy truck driver", selected: false},
        {key: "highway maintenance worker", value: "highway maintenance worker", selected: false},
        {key: "historian", value: "historian", selected: false},
        {key: "history teacher", value: "history teacher", selected: false},
        {key: "hoist and winch operator", value: "hoist and winch operator", selected: false},
        {key: "home appliance repairer", value: "home appliance repairer", selected: false},
        {key: "home economics teacher", value: "home economics teacher", selected: false},
        {key: "home entertainment installer", value: "home entertainment installer", selected: false},
        {key: "home health aide", value: "home health aide", selected: false},
        {key: "home management advisor", value: "home management advisor", selected: false},
        {key: "host", value: "host", selected: false},
        {key: "hostess", value: "hostess", selected: false},
        {key: "hostler", value: "hostler", selected: false},
        {key: "hotel desk clerk", value: "hotel desk clerk", selected: false},
        {key: "housekeeping cleaner", value: "housekeeping cleaner", selected: false},
        {key: "human resources assistant", value: "human resources assistant", selected: false},
        {key: "human resources manager", value: "human resources manager", selected: false},
        {key: "human service assistant", value: "human service assistant", selected: false},
        {key: "hunter", value: "hunter", selected: false},
        {key: "hydrologist", value: "hydrologist", selected: false},
        {key: "illustrator", value: "illustrator", selected: false},
        {key: "industrial designer", value: "industrial designer", selected: false},
        {key: "industrial engineer", value: "industrial engineer", selected: false},
        {key: "industrial engineering technician", value: "industrial engineering technician", selected: false},
        {key: "industrial machinery mechanic", value: "industrial machinery mechanic", selected: false},
        {key: "industrial production manager", value: "industrial production manager", selected: false},
        {key: "industrial truck operator", value: "industrial truck operator", selected: false},
        {key: "industrial-organizational psychologist", value: "industrial-organizational psychologist", selected: false},
        {key: "information clerk", value: "information clerk", selected: false},
        {key: "information research scientist", value: "information research scientist", selected: false},
        {key: "information security analyst", value: "information security analyst", selected: false},
        {key: "information systems manager", value: "information systems manager", selected: false},
        {key: "inspector", value: "inspector", selected: false},
        {key: "instructional coordinator", value: "instructional coordinator", selected: false},
        {key: "instructor", value: "instructor", selected: false},
        {key: "insulation worker", value: "insulation worker", selected: false},
        {key: "insurance claims clerk", value: "insurance claims clerk", selected: false},
        {key: "insurance sales agent", value: "insurance sales agent", selected: false},
        {key: "insurance underwriter", value: "insurance underwriter", selected: false},
        {key: "intercity bus driver", value: "intercity bus driver", selected: false},
        {key: "interior designer", value: "interior designer", selected: false},
        {key: "internist", value: "internist", selected: false},
        {key: "interpreter", value: "interpreter", selected: false},
        {key: "interviewer", value: "interviewer", selected: false},
        {key: "investigator", value: "investigator", selected: false},
        {key: "jailer", value: "jailer", selected: false},
        {key: "janitor", value: "janitor", selected: false},
        {key: "jeweler", value: "jeweler", selected: false},
        {key: "judge", value: "judge", selected: false},
        {key: "judicial law clerk", value: "judicial law clerk", selected: false},
        {key: "kettle operator", value: "kettle operator", selected: false},
        {key: "kiln operator", value: "kiln operator", selected: false},
        {key: "kindergarten teacher", value: "kindergarten teacher", selected: false},
        {key: "laboratory animal caretaker", value: "laboratory animal caretaker", selected: false},
        {key: "landscape architect", value: "landscape architect", selected: false},
        {key: "landscaping worker", value: "landscaping worker", selected: false},
        {key: "lathe setter", value: "lathe setter", selected: false},
        {key: "laundry worker", value: "laundry worker", selected: false},
        {key: "law enforcement teacher", value: "law enforcement teacher", selected: false},
        {key: "law teacher", value: "law teacher", selected: false},
        {key: "lawyer", value: "lawyer", selected: false},
        {key: "layout worker", value: "layout worker", selected: false},
        {key: "leather worker", value: "leather worker", selected: false},
        {key: "legal assistant", value: "legal assistant", selected: false},
        {key: "legal secretary", value: "legal secretary", selected: false},
        {key: "legislator", value: "legislator", selected: false},
        {key: "librarian", value: "librarian", selected: false},
        {key: "library assistant", value: "library assistant", selected: false},
        {key: "library science teacher", value: "library science teacher", selected: false},
        {key: "library technician", value: "library technician", selected: false},
        {key: "licensed practical nurse", value: "licensed practical nurse", selected: false},
        {key: "licensed vocational nurse", value: "licensed vocational nurse", selected: false},
        {key: "life scientist", value: "life scientist", selected: false},
        {key: "lifeguard", value: "lifeguard", selected: false},
        {key: "light truck driver", value: "light truck driver", selected: false},
        {key: "line installer", value: "line installer", selected: false},
        {key: "literacy teacher", value: "literacy teacher", selected: false},
        {key: "literature teacher", value: "literature teacher", selected: false},
        {key: "loading machine operator", value: "loading machine operator", selected: false},
        {key: "loan clerk", value: "loan clerk", selected: false},
        {key: "loan interviewer", value: "loan interviewer", selected: false},
        {key: "loan officer", value: "loan officer", selected: false},
        {key: "lobby attendant", value: "lobby attendant", selected: false},
        {key: "locker room attendant", value: "locker room attendant", selected: false},
        {key: "locksmith", value: "locksmith", selected: false},
        {key: "locomotive engineer", value: "locomotive engineer", selected: false},
        {key: "locomotive firer", value: "locomotive firer", selected: false},
        {key: "lodging manager", value: "lodging manager", selected: false},
        {key: "log grader", value: "log grader", selected: false},
        {key: "logging equipment operator", value: "logging equipment operator", selected: false},
        {key: "logistician", value: "logistician", selected: false},
        {key: "machine feeder", value: "machine feeder", selected: false},
        {key: "machinist", value: "machinist", selected: false},
        {key: "magistrate judge", value: "magistrate judge", selected: false},
        {key: "magistrate", value: "magistrate", selected: false},
        {key: "maid", value: "maid", selected: false},
        {key: "mail clerk", value: "mail clerk", selected: false},
        {key: "mail machine operator", value: "mail machine operator", selected: false},
        {key: "mail superintendent", value: "mail superintendent", selected: false},
        {key: "maintenance painter", value: "maintenance painter", selected: false},
        {key: "maintenance worker", value: "maintenance worker", selected: false},
        {key: "makeup artist", value: "makeup artist", selected: false},
        {key: "management analyst", value: "management analyst", selected: false},
        {key: "manicurist", value: "manicurist", selected: false},
        {key: "manufactured building installer", value: "manufactured building installer", selected: false},
        {key: "mapping technician", value: "mapping technician", selected: false},
        {key: "marble setter", value: "marble setter", selected: false},
        {key: "marine engineer", value: "marine engineer", selected: false},
        {key: "marine oiler", value: "marine oiler", selected: false},
        {key: "market research analyst", value: "market research analyst", selected: false},
        {key: "marketing manager", value: "marketing manager", selected: false},
        {key: "marketing specialist", value: "marketing specialist", selected: false},
        {key: "marriage therapist", value: "marriage therapist", selected: false},
        {key: "massage therapist", value: "massage therapist", selected: false},
        {key: "material mover", value: "material mover", selected: false},
        {key: "materials engineer", value: "materials engineer", selected: false},
        {key: "materials scientist", value: "materials scientist", selected: false},
        {key: "mathematical science teacher", value: "mathematical science teacher", selected: false},
        {key: "mathematical technician", value: "mathematical technician", selected: false},
        {key: "mathematician", value: "mathematician", selected: false},
        {key: "maxillofacial surgeon", value: "maxillofacial surgeon", selected: false},
        {key: "measurer", value: "measurer", selected: false},
        {key: "meat cutter", value: "meat cutter", selected: false},
        {key: "meat packer", value: "meat packer", selected: false},
        {key: "meat trimmer", value: "meat trimmer", selected: false},
        {key: "mechanical door repairer", value: "mechanical door repairer", selected: false},
        {key: "mechanical drafter", value: "mechanical drafter", selected: false},
        {key: "mechanical engineer", value: "mechanical engineer", selected: false},
        {key: "mechanical engineering technician", value: "mechanical engineering technician", selected: false},
        {key: "mediator", value: "mediator", selected: false},
        {key: "medical appliance technician", value: "medical appliance technician", selected: false},
        {key: "medical assistant", value: "medical assistant", selected: false},
        {key: "medical equipment preparer", value: "medical equipment preparer", selected: false},
        {key: "medical equipment repairer", value: "medical equipment repairer", selected: false},
        {key: "medical laboratory technician", value: "medical laboratory technician", selected: false},
        {key: "medical laboratory technologist", value: "medical laboratory technologist", selected: false},
        {key: "medical records technician", value: "medical records technician", selected: false},
        {key: "medical scientist", value: "medical scientist", selected: false},
        {key: "medical secretary", value: "medical secretary", selected: false},
        {key: "medical services manager", value: "medical services manager", selected: false},
        {key: "medical transcriptionist", value: "medical transcriptionist", selected: false},
        {key: "meeting planner", value: "meeting planner", selected: false},
        {key: "mental health counselor", value: "mental health counselor", selected: false},
        {key: "mental health social worker", value: "mental health social worker", selected: false},
        {key: "merchandise displayer", value: "merchandise displayer", selected: false},
        {key: "messenger", value: "messenger", selected: false},
        {key: "metal caster", value: "metal caster", selected: false},
        {key: "metal patternmaker", value: "metal patternmaker", selected: false},
        {key: "metal pickling operator", value: "metal pickling operator", selected: false},
        {key: "metal pourer", value: "metal pourer", selected: false},
        {key: "metal worker", value: "metal worker", selected: false},
        {key: "metal-refining furnace operator", value: "metal-refining furnace operator", selected: false},
        {key: "metal-refining furnace tender", value: "metal-refining furnace tender", selected: false},
        {key: "meter reader", value: "meter reader", selected: false},
        {key: "microbiologist", value: "microbiologist", selected: false},
        {key: "middle school teacher", value: "middle school teacher", selected: false},
        {key: "milling machine setter", value: "milling machine setter", selected: false},
        {key: "millwright", value: "millwright", selected: false},
        {key: "mine cutting machine operator", value: "mine cutting machine operator", selected: false},
        {key: "mine shuttle car operator", value: "mine shuttle car operator", selected: false},
        {key: "mining engineer", value: "mining engineer", selected: false},
        {key: "mining safety engineer", value: "mining safety engineer", selected: false},
        {key: "mining safety inspector", value: "mining safety inspector", selected: false},
        {key: "mining service unit operator", value: "mining service unit operator", selected: false},
        {key: "mixing machine setter", value: "mixing machine setter", selected: false},
        {key: "mobile heavy equipment mechanic", value: "mobile heavy equipment mechanic", selected: false},
        {key: "mobile home installer", value: "mobile home installer", selected: false},
        {key: "model maker", value: "model maker", selected: false},
        {key: "model", value: "model", selected: false},
        {key: "molder", value: "molder", selected: false},
        {key: "mortician", value: "mortician", selected: false},
        {key: "motel desk clerk", value: "motel desk clerk", selected: false},
        {key: "motion picture projectionist", value: "motion picture projectionist", selected: false},
        {key: "motorboat mechanic", value: "motorboat mechanic", selected: false},
        {key: "motorboat operator", value: "motorboat operator", selected: false},
        {key: "motorboat service technician", value: "motorboat service technician", selected: false},
        {key: "motorcycle mechanic", value: "motorcycle mechanic", selected: false},
        {key: "multimedia artist", value: "multimedia artist", selected: false},
        {key: "museum technician", value: "museum technician", selected: false},
        {key: "music director", value: "music director", selected: false},
        {key: "music teacher", value: "music teacher", selected: false},
        {key: "musical instrument repairer", value: "musical instrument repairer", selected: false},
        {key: "musician", value: "musician", selected: false},
        {key: "natural sciences manager", value: "natural sciences manager", selected: false},
        {key: "naval architect", value: "naval architect", selected: false},
        {key: "network systems administrator", value: "network systems administrator", selected: false},
        {key: "new accounts clerk", value: "new accounts clerk", selected: false},
        {key: "news vendor", value: "news vendor", selected: false},
        {key: "nonfarm animal caretaker", value: "nonfarm animal caretaker", selected: false},
        {key: "nuclear engineer", value: "nuclear engineer", selected: false},
        {key: "nuclear medicine technologist", value: "nuclear medicine technologist", selected: false},
        {key: "nuclear power reactor operator", value: "nuclear power reactor operator", selected: false},
        {key: "nuclear technician", value: "nuclear technician", selected: false},
        {key: "nursing aide", value: "nursing aide", selected: false},
        {key: "nursing instructor", value: "nursing instructor", selected: false},
        {key: "nursing teacher", value: "nursing teacher", selected: false},
        {key: "nutritionist", value: "nutritionist", selected: false},
        {key: "obstetrician", value: "obstetrician", selected: false},
        {key: "occupational health and safety specialist", value: "occupational health and safety specialist", selected: false},
        {key: "occupational health and safety technician", value: "occupational health and safety technician", selected: false},
        {key: "occupational therapist", value: "occupational therapist", selected: false},
        {key: "occupational therapy aide", value: "occupational therapy aide", selected: false},
        {key: "occupational therapy assistant", value: "occupational therapy assistant", selected: false},
        {key: "offbearer", value: "offbearer", selected: false},
        {key: "office clerk", value: "office clerk", selected: false},
        {key: "office machine operator", value: "office machine operator", selected: false},
        {key: "operating engineer", value: "operating engineer", selected: false},
        {key: "operations manager", value: "operations manager", selected: false},
        {key: "operations research analyst", value: "operations research analyst", selected: false},
        {key: "ophthalmic laboratory technician", value: "ophthalmic laboratory technician", selected: false},
        {key: "optician", value: "optician", selected: false},
        {key: "optometrist", value: "optometrist", selected: false},
        {key: "oral surgeon", value: "oral surgeon", selected: false},
        {key: "order clerk", value: "order clerk", selected: false},
        {key: "order filler", value: "order filler", selected: false},
        {key: "orderly", value: "orderly", selected: false},
        {key: "ordnance handling expert", value: "ordnance handling expert", selected: false},
        {key: "orthodontist", value: "orthodontist", selected: false},
        {key: "orthotist", value: "orthotist", selected: false},
        {key: "outdoor power equipment mechanic", value: "outdoor power equipment mechanic", selected: false},
        {key: "oven operator", value: "oven operator", selected: false},
        {key: "packaging machine operator", value: "packaging machine operator", selected: false},
        {key: "painter ", value: "painter ", selected: false},
        {key: "painting worker", value: "painting worker", selected: false},
        {key: "paper goods machine setter", value: "paper goods machine setter", selected: false},
        {key: "paperhanger", value: "paperhanger", selected: false},
        {key: "paralegal", value: "paralegal", selected: false},
        {key: "paramedic", value: "paramedic", selected: false},
        {key: "parking enforcement worker", value: "parking enforcement worker", selected: false},
        {key: "parking lot attendant", value: "parking lot attendant", selected: false},
        {key: "parts salesperson", value: "parts salesperson", selected: false},
        {key: "paving equipment operator", value: "paving equipment operator", selected: false},
        {key: "payroll clerk", value: "payroll clerk", selected: false},
        {key: "pediatrician", value: "pediatrician", selected: false},
        {key: "pedicurist", value: "pedicurist", selected: false},
        {key: "personal care aide", value: "personal care aide", selected: false},
        {key: "personal chef", value: "personal chef", selected: false},
        {key: "personal financial advisor", value: "personal financial advisor", selected: false},
        {key: "pest control worker", value: "pest control worker", selected: false},
        {key: "pesticide applicator", value: "pesticide applicator", selected: false},
        {key: "pesticide handler", value: "pesticide handler", selected: false},
        {key: "pesticide sprayer", value: "pesticide sprayer", selected: false},
        {key: "petroleum engineer", value: "petroleum engineer", selected: false},
        {key: "petroleum gauger", value: "petroleum gauger", selected: false},
        {key: "petroleum pump system operator", value: "petroleum pump system operator", selected: false},
        {key: "petroleum refinery operator", value: "petroleum refinery operator", selected: false},
        {key: "petroleum technician", value: "petroleum technician", selected: false},
        {key: "pharmacist", value: "pharmacist", selected: false},
        {key: "pharmacy aide", value: "pharmacy aide", selected: false},
        {key: "pharmacy technician", value: "pharmacy technician", selected: false},
        {key: "philosophy teacher", value: "philosophy teacher", selected: false},
        {key: "photogrammetrist", value: "photogrammetrist", selected: false},
        {key: "photographer", value: "photographer", selected: false},
        {key: "photographic process worker", value: "photographic process worker", selected: false},
        {key: "photographic processing machine operator", value: "photographic processing machine operator", selected: false},
        {key: "physical therapist aide", value: "physical therapist aide", selected: false},
        {key: "physical therapist assistant", value: "physical therapist assistant", selected: false},
        {key: "physical therapist", value: "physical therapist", selected: false},
        {key: "physician assistant", value: "physician assistant", selected: false},
        {key: "physician", value: "physician", selected: false},
        {key: "physicist", value: "physicist", selected: false},
        {key: "physics teacher", value: "physics teacher", selected: false},
        {key: "pile-driver operator", value: "pile-driver operator", selected: false},
        {key: "pipefitter", value: "pipefitter", selected: false},
        {key: "pipelayer", value: "pipelayer", selected: false},
        {key: "planing machine operator", value: "planing machine operator", selected: false},
        {key: "planning clerk", value: "planning clerk", selected: false},
        {key: "plant operator", value: "plant operator", selected: false},
        {key: "plant scientist", value: "plant scientist", selected: false},
        {key: "plasterer", value: "plasterer", selected: false},
        {key: "plastic patternmaker", value: "plastic patternmaker", selected: false},
        {key: "plastic worker", value: "plastic worker", selected: false},
        {key: "plumber", value: "plumber", selected: false},
        {key: "podiatrist", value: "podiatrist", selected: false},
        {key: "police dispatcher", value: "police dispatcher", selected: false},
        {key: "police officer", value: "police officer", selected: false},
        {key: "policy processing clerk", value: "policy processing clerk", selected: false},
        {key: "political science teacher", value: "political science teacher", selected: false},
        {key: "political scientist", value: "political scientist", selected: false},
        {key: "postal service clerk", value: "postal service clerk", selected: false},
        {key: "postal service mail carrier", value: "postal service mail carrier", selected: false},
        {key: "postal service mail processing machine operator", value: "postal service mail processing machine operator", selected: false},
        {key: "postal service mail processor", value: "postal service mail processor", selected: false},
        {key: "postal service mail sorter", value: "postal service mail sorter", selected: false},
        {key: "postmaster", value: "postmaster", selected: false},
        {key: "postsecondary teacher", value: "postsecondary teacher", selected: false},
        {key: "poultry cutter", value: "poultry cutter", selected: false},
        {key: "poultry trimmer", value: "poultry trimmer", selected: false},
        {key: "power dispatcher", value: "power dispatcher", selected: false},
        {key: "power distributor", value: "power distributor", selected: false},
        {key: "power plant operator", value: "power plant operator", selected: false},
        {key: "power tool repairer", value: "power tool repairer", selected: false},
        {key: "precious stone worker", value: "precious stone worker", selected: false},
        {key: "precision instrument repairer", value: "precision instrument repairer", selected: false},
        {key: "prepress technician", value: "prepress technician", selected: false},
        {key: "preschool teacher", value: "preschool teacher", selected: false},
        {key: "priest", value: "priest", selected: false},
        {key: "print binding worker", value: "print binding worker", selected: false},
        {key: "printing press operator", value: "printing press operator", selected: false},
        {key: "private detective", value: "private detective", selected: false},
        {key: "probation officer", value: "probation officer", selected: false},
        {key: "procurement clerk", value: "procurement clerk", selected: false},
        {key: "producer", value: "producer", selected: false},
        {key: "product promoter", value: "product promoter", selected: false},
        {key: "production clerk", value: "production clerk", selected: false},
        {key: "production occupation", value: "production occupation", selected: false},
        {key: "proofreader", value: "proofreader", selected: false},
        {key: "property manager", value: "property manager", selected: false},
        {key: "prosthetist", value: "prosthetist", selected: false},
        {key: "prosthodontist", value: "prosthodontist", selected: false},
        {key: "psychiatric aide", value: "psychiatric aide", selected: false},
        {key: "psychiatric technician", value: "psychiatric technician", selected: false},
        {key: "psychiatrist", value: "psychiatrist", selected: false},
        {key: "psychologist", value: "psychologist", selected: false},
        {key: "psychology teacher", value: "psychology teacher", selected: false},
        {key: "public relations manager", value: "public relations manager", selected: false},
        {key: "public relations specialist", value: "public relations specialist", selected: false},
        {key: "pump operator", value: "pump operator", selected: false},
        {key: "purchasing agent", value: "purchasing agent", selected: false},
        {key: "purchasing manager", value: "purchasing manager", selected: false},
        {key: "radiation therapist", value: "radiation therapist", selected: false},
        {key: "radio announcer", value: "radio announcer", selected: false},
        {key: "radio equipment installer", value: "radio equipment installer", selected: false},
        {key: "radio operator", value: "radio operator", selected: false},
        {key: "radiologic technician", value: "radiologic technician", selected: false},
        {key: "radiologic technologist", value: "radiologic technologist", selected: false},
        {key: "rail car repairer", value: "rail car repairer", selected: false},
        {key: "rail transportation worker", value: "rail transportation worker", selected: false},
        {key: "rail yard engineer", value: "rail yard engineer", selected: false},
        {key: "rail-track laying equipment operator", value: "rail-track laying equipment operator", selected: false},
        {key: "railroad brake operator", value: "railroad brake operator", selected: false},
        {key: "railroad conductor", value: "railroad conductor", selected: false},
        {key: "railroad police", value: "railroad police", selected: false},
        {key: "rancher", value: "rancher", selected: false},
        {key: "real estate appraiser", value: "real estate appraiser", selected: false},
        {key: "real estate broker", value: "real estate broker", selected: false},
        {key: "real estate manager", value: "real estate manager", selected: false},
        {key: "real estate sales agent", value: "real estate sales agent", selected: false},
        {key: "receiving clerk", value: "receiving clerk", selected: false},
        {key: "receptionist", value: "receptionist", selected: false},
        {key: "record clerk", value: "record clerk", selected: false},
        {key: "recreation teacher", value: "recreation teacher", selected: false},
        {key: "recreation worker", value: "recreation worker", selected: false},
        {key: "recreational therapist", value: "recreational therapist", selected: false},
        {key: "recreational vehicle service technician", value: "recreational vehicle service technician", selected: false},
        {key: "recyclable material collector", value: "recyclable material collector", selected: false},
        {key: "referee", value: "referee", selected: false},
        {key: "refractory materials repairer", value: "refractory materials repairer", selected: false},
        {key: "refrigeration installer", value: "refrigeration installer", selected: false},
        {key: "refrigeration mechanic", value: "refrigeration mechanic", selected: false},
        {key: "refuse collector", value: "refuse collector", selected: false},
        {key: "regional planner", value: "regional planner", selected: false},
        {key: "registered nurse", value: "registered nurse", selected: false},
        {key: "rehabilitation counselor", value: "rehabilitation counselor", selected: false},
        {key: "reinforcing iron worker", value: "reinforcing iron worker", selected: false},
        {key: "reinforcing rebar worker", value: "reinforcing rebar worker", selected: false},
        {key: "religion teacher", value: "religion teacher", selected: false},
        {key: "religious activities director", value: "religious activities director", selected: false},
        {key: "religious worker", value: "religious worker", selected: false},
        {key: "rental clerk", value: "rental clerk", selected: false},
        {key: "repair worker", value: "repair worker", selected: false},
        {key: "reporter", value: "reporter", selected: false},
        {key: "residential advisor", value: "residential advisor", selected: false},
        {key: "resort desk clerk", value: "resort desk clerk", selected: false},
        {key: "respiratory therapist", value: "respiratory therapist", selected: false},
        {key: "respiratory therapy technician", value: "respiratory therapy technician", selected: false},
        {key: "retail buyer", value: "retail buyer", selected: false},
        {key: "retail salesperson", value: "retail salesperson", selected: false},
        {key: "revenue agent", value: "revenue agent", selected: false},
        {key: "rigger", value: "rigger", selected: false},
        {key: "rock splitter", value: "rock splitter", selected: false},
        {key: "rolling machine tender", value: "rolling machine tender", selected: false},
        {key: "roof bolter", value: "roof bolter", selected: false},
        {key: "roofer", value: "roofer", selected: false},
        {key: "rotary drill operator", value: "rotary drill operator", selected: false},
        {key: "roustabout", value: "roustabout", selected: false},
        {key: "safe repairer", value: "safe repairer", selected: false},
        {key: "sailor", value: "sailor", selected: false},
        {key: "sales engineer", value: "sales engineer", selected: false},
        {key: "sales manager", value: "sales manager", selected: false},
        {key: "sales representative", value: "sales representative", selected: false},
        {key: "sampler", value: "sampler", selected: false},
        {key: "sawing machine operator", value: "sawing machine operator", selected: false},
        {key: "scaler", value: "scaler", selected: false},
        {key: "school bus driver", value: "school bus driver", selected: false},
        {key: "school psychologist", value: "school psychologist", selected: false},
        {key: "school social worker", value: "school social worker", selected: false},
        {key: "scout leader", value: "scout leader", selected: false},
        {key: "sculptor", value: "sculptor", selected: false},
        {key: "secondary education teacher", value: "secondary education teacher", selected: false},
        {key: "secondary school teacher", value: "secondary school teacher", selected: false},
        {key: "secretary", value: "secretary", selected: false},
        {key: "securities sales agent", value: "securities sales agent", selected: false},
        {key: "security guard", value: "security guard", selected: false},
        {key: "security system installer", value: "security system installer", selected: false},
        {key: "segmental paver", value: "segmental paver", selected: false},
        {key: "self-enrichment education teacher", value: "self-enrichment education teacher", selected: false},
        {key: "semiconductor processor", value: "semiconductor processor", selected: false},
        {key: "septic tank servicer", value: "septic tank servicer", selected: false},
        {key: "set designer", value: "set designer", selected: false},
        {key: "sewer pipe cleaner", value: "sewer pipe cleaner", selected: false},
        {key: "sewing machine operator", value: "sewing machine operator", selected: false},
        {key: "shampooer", value: "shampooer", selected: false},
        {key: "shaper", value: "shaper", selected: false},
        {key: "sheet metal worker", value: "sheet metal worker", selected: false},
        {key: "sheriff's patrol officer", value: "sheriff's patrol officer", selected: false},
        {key: "ship captain", value: "ship captain", selected: false},
        {key: "ship engineer", value: "ship engineer", selected: false},
        {key: "ship loader", value: "ship loader", selected: false},
        {key: "shipmate", value: "shipmate", selected: false},
        {key: "shipping clerk", value: "shipping clerk", selected: false},
        {key: "shoe machine operator", value: "shoe machine operator", selected: false},
        {key: "shoe worker", value: "shoe worker", selected: false},
        {key: "short order cook", value: "short order cook", selected: false},
        {key: "signal operator", value: "signal operator", selected: false},
        {key: "signal repairer", value: "signal repairer", selected: false},
        {key: "singer", value: "singer", selected: false},
        {key: "ski patrol", value: "ski patrol", selected: false},
        {key: "skincare specialist", value: "skincare specialist", selected: false},
        {key: "slaughterer", value: "slaughterer", selected: false},
        {key: "slicing machine tender", value: "slicing machine tender", selected: false},
        {key: "slot supervisor", value: "slot supervisor", selected: false},
        {key: "social science research assistant", value: "social science research assistant", selected: false},
        {key: "social sciences teacher", value: "social sciences teacher", selected: false},
        {key: "social scientist", value: "social scientist", selected: false},
        {key: "social service assistant", value: "social service assistant", selected: false},
        {key: "social service manager", value: "social service manager", selected: false},
        {key: "social work teacher", value: "social work teacher", selected: false},
        {key: "social worker", value: "social worker", selected: false},
        {key: "sociologist", value: "sociologist", selected: false},
        {key: "sociology teacher", value: "sociology teacher", selected: false},
        {key: "software developer", value: "software developer", selected: false},
        {key: "software engineer", value: "software engineer", selected: false},
        {key: "soil scientist", value: "soil scientist", selected: false},
        {key: "solderer", value: "solderer", selected: false},
        {key: "sorter", value: "sorter", selected: false},
        {key: "sound engineering technician", value: "sound engineering technician", selected: false},
        {key: "space scientist", value: "space scientist", selected: false},
        {key: "special education teacher", value: "special education teacher", selected: false},
        {key: "speech-language pathologist", value: "speech-language pathologist", selected: false},
        {key: "sports book runner", value: "sports book runner", selected: false},
        {key: "sports entertainer", value: "sports entertainer", selected: false},
        {key: "sports performer", value: "sports performer", selected: false},
        {key: "stationary engineer", value: "stationary engineer", selected: false},
        {key: "statistical assistant", value: "statistical assistant", selected: false},
        {key: "statistician", value: "statistician", selected: false},
        {key: "steamfitter", value: "steamfitter", selected: false},
        {key: "stock clerk", value: "stock clerk", selected: false},
        {key: "stock mover", value: "stock mover", selected: false},
        {key: "stonemason", value: "stonemason", selected: false},
        {key: "street vendor", value: "street vendor", selected: false},
        {key: "streetcar operator", value: "streetcar operator", selected: false},
        {key: "structural iron worker", value: "structural iron worker", selected: false},
        {key: "structural metal fabricator", value: "structural metal fabricator", selected: false},
        {key: "structural metal fitter", value: "structural metal fitter", selected: false},
        {key: "structural steel worker", value: "structural steel worker", selected: false},
        {key: "stucco mason", value: "stucco mason", selected: false},
        {key: "substance abuse counselor", value: "substance abuse counselor", selected: false},
        {key: "substance abuse social worker", value: "substance abuse social worker", selected: false},
        {key: "subway operator", value: "subway operator", selected: false},
        {key: "surfacing equipment operator", value: "surfacing equipment operator", selected: false},
        {key: "surgeon", value: "surgeon", selected: false},
        {key: "surgical technologist", value: "surgical technologist", selected: false},
        {key: "survey researcher", value: "survey researcher", selected: false},
        {key: "surveying technician", value: "surveying technician", selected: false},
        {key: "surveyor", value: "surveyor", selected: false},
        {key: "switch operator", value: "switch operator", selected: false},
        {key: "switchboard operator", value: "switchboard operator", selected: false},
        {key: "tailor", value: "tailor", selected: false},
        {key: "tamping equipment operator", value: "tamping equipment operator", selected: false},
        {key: "tank car loader", value: "tank car loader", selected: false},
        {key: "taper", value: "taper", selected: false},
        {key: "tax collector", value: "tax collector", selected: false},
        {key: "tax examiner", value: "tax examiner", selected: false},
        {key: "tax preparer", value: "tax preparer", selected: false},
        {key: "taxi driver", value: "taxi driver", selected: false},
        {key: "teacher assistant", value: "teacher assistant", selected: false},
        {key: "teacher", value: "teacher", selected: false},
        {key: "team assembler", value: "team assembler", selected: false},
        {key: "technical writer", value: "technical writer", selected: false},
        {key: "telecommunications equipment installer", value: "telecommunications equipment installer", selected: false},
        {key: "telemarketer", value: "telemarketer", selected: false},
        {key: "telephone operator", value: "telephone operator", selected: false},
        {key: "television announcer", value: "television announcer", selected: false},
        {key: "teller", value: "teller", selected: false},
        {key: "terrazzo finisher", value: "terrazzo finisher", selected: false},
        {key: "terrazzo worker", value: "terrazzo worker", selected: false},
        {key: "tester", value: "tester", selected: false},
        {key: "textile bleaching operator", value: "textile bleaching operator", selected: false},
        {key: "textile cutting machine setter", value: "textile cutting machine setter", selected: false},
        {key: "textile knitting machine setter", value: "textile knitting machine setter", selected: false},
        {key: "textile presser", value: "textile presser", selected: false},
        {key: "textile worker", value: "textile worker", selected: false},
        {key: "therapist", value: "therapist", selected: false},
        {key: "ticket agent", value: "ticket agent", selected: false},
        {key: "ticket taker", value: "ticket taker", selected: false},
        {key: "tile setter", value: "tile setter", selected: false},
        {key: "timekeeping clerk", value: "timekeeping clerk", selected: false},
        {key: "timing device assembler", value: "timing device assembler", selected: false},
        {key: "tire builder", value: "tire builder", selected: false},
        {key: "tire changer", value: "tire changer", selected: false},
        {key: "tire repairer", value: "tire repairer", selected: false},
        {key: "title abstractor", value: "title abstractor", selected: false},
        {key: "title examiner", value: "title examiner", selected: false},
        {key: "title searcher", value: "title searcher", selected: false},
        {key: "tobacco roasting machine operator", value: "tobacco roasting machine operator", selected: false},
        {key: "tool filer", value: "tool filer", selected: false},
        {key: "tool grinder", value: "tool grinder", selected: false},
        {key: "tool maker", value: "tool maker", selected: false},
        {key: "tool sharpener", value: "tool sharpener", selected: false},
        {key: "tour guide", value: "tour guide", selected: false},
        {key: "tower equipment installer", value: "tower equipment installer", selected: false},
        {key: "tower operator", value: "tower operator", selected: false},
        {key: "track switch repairer", value: "track switch repairer", selected: false},
        {key: "tractor operator", value: "tractor operator", selected: false},
        {key: "tractor-trailer truck driver", value: "tractor-trailer truck driver", selected: false},
        {key: "traffic clerk", value: "traffic clerk", selected: false},
        {key: "traffic technician", value: "traffic technician", selected: false},
        {key: "training and development manager", value: "training and development manager", selected: false},
        {key: "training and development specialist", value: "training and development specialist", selected: false},
        {key: "transit police", value: "transit police", selected: false},
        {key: "translator", value: "translator", selected: false},
        {key: "transportation equipment painter", value: "transportation equipment painter", selected: false},
        {key: "transportation inspector", value: "transportation inspector", selected: false},
        {key: "transportation security screener", value: "transportation security screener", selected: false},
        {key: "transportation worker", value: "transportation worker", selected: false},
        {key: "trapper", value: "trapper", selected: false},
        {key: "travel agent", value: "travel agent", selected: false},
        {key: "travel clerk", value: "travel clerk", selected: false},
        {key: "travel guide", value: "travel guide", selected: false},
        {key: "tree pruner", value: "tree pruner", selected: false},
        {key: "tree trimmer", value: "tree trimmer", selected: false},
        {key: "trimmer", value: "trimmer", selected: false},
        {key: "truck loader", value: "truck loader", selected: false},
        {key: "truck mechanic", value: "truck mechanic", selected: false},
        {key: "tuner", value: "tuner", selected: false},
        {key: "turning machine tool operator", value: "turning machine tool operator", selected: false},
        {key: "typist", value: "typist", selected: false},
        {key: "umpire", value: "umpire", selected: false},
        {key: "undertaker", value: "undertaker", selected: false},
        {key: "upholsterer", value: "upholsterer", selected: false},
        {key: "urban planner", value: "urban planner", selected: false},
        {key: "usher", value: "usher", selected: false},
        {key: "valve installer", value: "valve installer", selected: false},
        {key: "vending machine servicer", value: "vending machine servicer", selected: false},
        {key: "veterinarian", value: "veterinarian", selected: false},
        {key: "veterinary assistant", value: "veterinary assistant", selected: false},
        {key: "veterinary technician", value: "veterinary technician", selected: false},
        {key: "vocational counselor", value: "vocational counselor", selected: false},
        {key: "vocational education teacher", value: "vocational education teacher", selected: false},
        {key: "waiter", value: "waiter", selected: false},
        {key: "waitress", value: "waitress", selected: false},
        {key: "watch repairer", value: "watch repairer", selected: false},
        {key: "water treatment plant operator", value: "water treatment plant operator", selected: false},
        {key: "weaving machine setter", value: "weaving machine setter", selected: false},
        {key: "web developer", value: "web developer", selected: false},
        {key: "weigher", value: "weigher", selected: false},
        {key: "welder", value: "welder", selected: false},
        {key: "wellhead pumper", value: "wellhead pumper", selected: false},
        {key: "wholesale buyer", value: "wholesale buyer", selected: false},
        {key: "wildlife biologist", value: "wildlife biologist", selected: false},
        {key: "window trimmer", value: "window trimmer", selected: false},
        {key: "wood patternmaker", value: "wood patternmaker", selected: false},
        {key: "woodworker", value: "woodworker", selected: false},
        {key: "word processor", value: "word processor", selected: false},
        {key: "writer", value: "writer", selected: false},
        {key: "yardmaster", value: "yardmaster", selected: false},
        {key: "zoologist", value: "zoologist", selected: false}
]
